/* MIZAN ANZAN — Final Global Locale */
/* Language: am | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["am"] = {
    brand_title: "MIZAN ANZAN",
    meta_description: "Mizan Anzan — ፕሮፌሽናል የአንዛን እና ሶሮባን ስልጠና መድረክ",
    language_selector_aria: "ቋንቋ ይምረጡ",
    answer_placeholder: "ውጤቱን እዚህ ያስገቡ",
    platform_subtitle: "የሰው ልማት ዓለም አቀፍ የሳይንስ ሊቃውንት ኮሚሽን መድረክ — ፈረንሳይ",
    nav_setup: "የስልጠና ቅንብሮች",
    nav_leaderboard: "መሪ ሰሌዳ (Top 20)",
    nav_trainer: "የአሰልጣኝ ፖርታል",
    nav_parent: "የወላጅ ፖርታል",
    nav_monthly: "የወሩ ተሰጥኦዎች",
    nav_history: "የስልጠና ታሪክ እና ሪፖርቶች",
    student_code_label: "የተሰጥኦ ኮድ:",
    reset_account: "ይመዝገቡ / መለያ ይቀይሩ",
    preset_kyu_dan_label: "አሰልጣኝ - የስልጠና ደረጃ ያዘጋጁ",
    preset_custom: "-- ብጁ በእጅ ማቀናበሪያ --",
    preset_kyu_beginner: "የጀማሪ ደረጃ (Kyu 10 - Kyu 7) | 1-2 አሃዞች - 3-5 ረድፎች",
    preset_kyu_inter: "መካከለኛ ደረጃ (Kyu 6 - Kyu 4) | 2-3 አሃዞች - 5-8 ረድፎች",
    preset_kyu_advanced: "የላቀ ደረጃ (Kyu 3 - Kyu 1) | 3-5 አሃዞች - 8-12 ረድፎች",
    preset_dan_pro: "ፕሮፌሽናል ደረጃ (Dan 1 - Dan 5) | 5-8 አሃዞች - 15-25 ረድፎች",
    preset_dan_master: "ማስተር ደረጃ (Dan 6 - Dan 10) | 8-10 አሃዞች - 30-50 ረድፎች",
    preset_olympiad_gm: "የዓለም ኦሊምፒያድ ደረጃ (ግራንድማስተር) | 10-15 አሃዞች - 50-100 ረድፎች",
    mode_label: "የስልጠና ሁነታ",
    mode_flash: "ፍላሽ አንዛን",
    mode_flash_desc: "ከፍተኛ ፍጥነት ቅደም ተከተላዊ ብልጭታ",
    mode_standard: "መደበኛ ሶሮባን (ስታቲክ)",
    mode_standard_desc: "ሙሉ የማይንቀሳቀሱ ቁጥሮች ማሳያ",
    level_label: "ደረጃ (ጥብቅ የሶሮባን ህጎች)",
    level_l1: "L1 - ቀጥተኛ መደመር/መቀነስ (ያለ ማሟያ)",
    level_l2: "L2 - የ5 ጓደኞች (5 ማሟያዎች)",
    level_l3: "L3 - የ10 ጓደኞች (10 ማሟያዎች)",
    level_lm: "LM - አጠቃላይ ድብልቅ (ሁሉም ህጎች)",
    age_label: "የዕድሜ ቡድን",
    age_under_6: "ከ6 ዓመት በታች",
    age_7_9: "7 - 9 ዓመት",
    age_10_12: "10 - 12 ዓመት",
    age_13_15: "13 - 15 ዓመት",
    age_16_plus: "16+ ዓመት",
    digits_label: "አሃዞች",
    rows_label: "ረድፎች",
    op_label: "የክወና አይነት",
    op_add: "መደመር ብቻ",
    op_sub: "መቀነስ ብቻ",
    op_mix: "ድብልቅ (መደመር እና መቀነስ)",
    duration_label: "የፈተና ጊዜ (ሴኮንድ)",
    rest_label: "የእረፍት ጊዜ",
    rest_1s: "1 ሴኮንድ",
    rest_2s: "2 ሴኮንድ",
    rest_3s: "3 ሴኮንድ",
    rest_4s: "4 ሴኮንድ",
    rest_5s: "5 ሴኮንድ",
    speed_label: "የማሳያ ፍጥነት (ሴኮንድ)",
    tts_label: "የቁጥር አጠራር",
    start_button: "ፈተና ጀምር",
    timer_label: "የቀረ ጊዜ:",
    score_label: "ነጥብ:",
    exit_button: "ውጣ",
    submit_answer: "መልስ አስገባ",
    welcome_title: "እንኳን ወደ Mizan Anzan በደህና መጡ",
    welcome_desc: "የክትትል ኮድዎን ለመፍጠር ዝርዝሮችዎን ይመዝገቡ",
    fullname_label: "የተሰጥኦው ሙሉ ስም",
    fullname_ph: "ሙሉ ስምዎን ያስገቡ",
    country_label: "ሀገር",
    country_ph: "ለምሳሌ: ፈረንሳይ, ግብፅ, ሳውዲ አረቢያ",
    generate_code_btn: "የተሰጥኦ ኮድ ፍጠር እና ግባ",
    countdown_start: "ጀምር!",
    generation_error: "በእነዚህ ቅንብሮች ትክክለኛ ፈተና መፍጠር አልተቻለም።",
    correct_feedback: "ትክክለኛ መልስ! ጥሩ ስራ, ተሰጥኦ.",
    incorrect_feedback: "ስህተት። ትክክለኛው መልስ:",
    invalid_integer: "እባክዎ ትክክለኛ ሙሉ ቁጥር ያስገቡ።",
    challenge_complete: "ፈተና ተጠናቀቀ!",
    total_score: "ጠቅላላ ነጥብ:",
    correct_answers: "ትክክለኛ መልሶች:",
    of_word: "ከ",
    trainer_title: "የአሰልጣኝ መቆጣጠሪያ ፓነል",
    parent_title: "የወላጅ እድገት ፓነል",
    portal_desc: "እድገት እና ዝርዝር ትንታኔ ለማየት የተሰጥኦ ኮድ ያስገቡ",
    lookup_placeholder: "የተሰጥኦ ኮድ ያስገቡ (ለምሳሌ: ANZ-982143)",
    follow_up: "ተመልከት",
    enter_code: "እባክዎ የተሰጥኦ ኮድ ያስገቡ",
    tracked_student: "የተከታተለው ተሰጥኦ:",
    active_account: "ንቁ የተመዘገበ መለያ",
    genius_fallback: "የአንዛን ተሰጥኦ",
    focus_metric: "ትኩረት",
    accuracy_metric: "ትክክለኛነት",
    perf_metric: "አፈጻጸም እና ፍጥነት",
    growth_metric: "እድገት",
    th_rank: "#",
    th_code: "ኮድ",
    th_country: "ሀገር",
    th_name: "የተሰጥኦ ስም",
    th_mode: "ሁነታ",
    th_age: "የዕድሜ ቡድን",
    th_level: "ደረጃ",
    th_digits: "አሃዞች",
    th_rows: "ረድፎች",
    th_operation: "ክወና",
    th_duration: "ቆይታ",
    th_speed: "ፍጥነት",
    th_points: "ነጥቦች",
    leaderboard_title: "መሪ ሰሌዳ — Top 20",
    leaderboard_empty: "እስካሁን ውጤት የለም።",
    mode_flash_short: "ፍላሽ አንዛን",
    mode_standard_short: "መደበኛ ሶሮባን",
    op_add_short: "መደመር",
    op_sub_short: "መቀነስ",
    op_mix_short: "ድብልቅ",
    subtract_speech: "መቀነስ",
    seconds_short: "ሴ",
    challenge_invalid: "ፈተናው ሊጀመር አልቻለም። ቅንብሮችን ይፈትሹ እና እንደገና ይሞክሩ።",
    challenge_generation_failed: "ፈተናው ሊፈጠር አልቻለም። ፈተናው አልተጀመረም። እባክዎ የስልጠና ቅንብሮችን ይፈትሹ።",
    save_failed: "የፈተና ውጤቱ በአገልጋዩ ላይ ሊቀመጥ አልቻለም። ይህ ሙከራ በሪፖርቶች ወይም በመሪ ሰሌዳ ላይ አልተቆጠረም።",
    save_success: "ውጤቱ በተሳካ ሁኔታ ተቀምጧል እና ከተማሪ ኮድ ጋር ተገናኝቷል።",
    save_queued: "አገልጋዩ ለጊዜው አይገኝም። ይህ ሙከራ በአካባቢው ተቀምጧል እና ግንኙነቱ ሲመለስ በራስ-ሰር ይመሳሰላል።",
    open_report_prompt: "ሪፖርቱን አሁን መክፈት ይፈልጋሉ?",
    loading_data: "ውሂብ በመጫን ላይ...",
    monthly_failed: "የወሩ ተሰጥኦዎች መጫን አልተቻለም።",
    monthly_title: "የወሩ ተሰጥኦዎች",
    sessions_metric: "ክፍለ-ጊዜዎች",
    questions_metric: "ጥያቄዎች",
    points_metric: "ነጥቦች",
    streak_metric: "ምርጥ ተከታታይ",
    student_not_found: "ተማሪው አልተገኘም ወይም ውሂቡ መጫን አልቻለም።",
    result_title: "ፈተና ተጠናቀቀ!",
    result_subtitle: "የፈተና ውጤትዎ ለግምገማ ዝግጁ ነው።",
    result_score: "ጠቅላላ ነጥብ:",
    result_correct: "ትክክለኛ መልሶች:",
    result_saved: "ውጤቱ በተሳካ ሁኔታ ተቀምጧል እና ከተማሪ ኮድ ጋር ተገናኝቷል።",
    result_open_report: "ሪፖርት ክፈት",
    result_continue: "ቀጥል",
    version_label: "Soroban Core v3.1",
    registration_title: "እንኳን ወደ MIZAN ANZAN በደህና መጡ",
    registration_desc: "የእርስዎን ደህንነቱ የተጠበቀ MIZAN ማንነት ይፍጠሩ እና ወደ ግላዊ የመማሪያ ጉዞዎ ይቀጥሉ።",
    registration_language_label: "የምዝገባ ቋንቋ",
    registration_language_desc: "በ MIZAN ልምድዎ ውስጥ መጠቀም የሚፈልጉትን ቋንቋ ይምረጡ።",
    role_selection_title: "የመለያ አይነትዎን ይምረጡ",
    role_selection_desc: "MIZAN ን እንዴት እንደሚጠቀሙ በተሻለ ሁኔታ የሚገልጽ የመለያ አይነት ይምረጡ።",
    role_genius: "ብልህ",
    role_genius_desc: "ለማሰልጠን፣ ለማሻሻል እና የራሳቸውን እድገት ለመከታተል ለሚፈልጉ ተማሪዎች።",
    role_coach: "አሰልጣኝ",
    role_coach_desc: "ትምህርትን፣ ስልጠናን እና የተማሪዎችን እድገት ለሚያስተዳድሩ አሰልጣኞች።",
    role_parent: "ወላጅ",
    role_parent_desc: "የልጃቸውን እድገት መከታተል ለሚፈልጉ ወላጆች ወይም አሳዳጊዎች።",
    role_entity: "ድርጅት",
    role_entity_desc: "ለትምህርት ቤቶች፣ አካዳሚዎች፣ ማእከላት፣ ተቋማት፣ ክለቦች፣ ፌዴሬሽኖች እና የስልጠና ድርጅቶች።",
    genius_full_name_label: "የብልህ ሙሉ ስም",
    genius_full_name_placeholder: "ሙሉ ስምዎን ያስገቡ",
    display_name_en_label: "በእንግሊዝኛ ዓለም አቀፍ ስም",
    display_name_en_placeholder: "ስምዎን በእንግሊዝኛ ያስገቡ",
    display_name_en_help: "ይህ ስም በዓለም አቀፍ የመሪ ሰንጠረዦች፣ ውድድሮች እና ዓለም አቀፍ እውቅና ላይ ጥቅም ላይ ይውላል።",
    display_name_en_required: "የእርስዎ ዓለም አቀፍ የእንግሊዝኛ ስም ያስፈልጋል።",
    display_name_en_invalid: "እባክዎን የእንግሊዝኛ ፊደላትን በመጠቀም ትክክለኛ ዓለም አቀፍ ስም ያስገቡ።",
    display_name_en_confirm: "ይህ በዓለም አቀፍ ደረጃ መጠቀም የምፈልገው የእንግሊዝኛ ስም መሆኑን አረጋግጣለሁ።",
    country_placeholder: "ሀገርዎን ይምረጡ",
    country_search_placeholder: "ሀገርዎን ይፈልጉ",
    country_help: "ሀገርዎ ለዓለም አቀፍ ደረጃዎች እና ውድድሮች ጥቅም ላይ ይውላል።",
    entity_name_label: "የድርጅት ስም",
    entity_name_placeholder: "የድርጅቱን ስም ያስገቡ",
    entity_type_label: "የድርጅት አይነት",
    branch_label: "ቅርንጫፍ",
    branch_placeholder: "ቅርንጫፍ ይምረጡ",
    branch_optional: "ቅርንጫፍ መምረጥ አማራጭ ነው",
    branch_main: "ዋና ድርጅት",
    independent_coach: "ገለልተኛ አሰልጣኝ",
    independent_coach_title: "ገለልተኛ አሰልጣኝ",
    independent_coach_desc: "ያለ ድርጅት በገለልተኛ አሰልጣኝነት ይመዝገቡ።",
    independent_coach_note: "ገለልተኛ አሰልጣኞች ያለ ድርጅት ወይም ቅርንጫፍ መመዝገብ ይችላሉ።",
    coach_registration_title: "የአሰልጣኝ ምዝገባ",
    coach_registration_desc: "የእርስዎን ፕሮፌሽናል MIZAN አሰልጣኝ መለያ ይፍጠሩ።",
    coach_code_label: "የአሰልጣኝ ኮድ",
    parent_registration_title: "የወላጅ ምዝገባ",
    parent_registration_desc: "የእርስዎን ደህንነቱ የተጠበቀ የወላጅ ወይም የአሳዳጊ መለያ ይፍጠሩ።",
    parent_code_label: "የወላጅ ኮድ",
    entity_code_label: "የድርጅት ኮድ",
    entity_code_placeholder: "የድርጅት ኮድዎን ያስገቡ",
    entity_code_help: "የድርጅትዎን MIZAN መለያ ለመድረስ ይህን ኮድ ይጠቀሙ።",
    create_account_button: "መለያ ይፍጠሩ",
    create_genius_account_button: "የብልህ መለያ ይፍጠሩ",
    create_coach_account_button: "የአሰልጣኝ መለያ ይፍጠሩ",
    create_parent_account_button: "የወላጅ መለያ ይፍጠሩ",
    create_organization_account_button: "የድርጅት መለያ ይፍጠሩ",
    registration_success_title: "ምዝገባ ተሳክቷል",
    registration_success_desc: "የእርስዎ MIZAN መለያ በተሳካ ሁኔታ ተፈጥሯል።",
    your_genius_code: "የእርስዎ የብልህ ኮድ",
    your_coach_code: "የእርስዎ የአሰልጣኝ ኮድ",
    your_parent_code: "የእርስዎ የወላጅ ኮድ",
    your_organization_code: "የእርስዎ የድርጅት ኮድ",
    save_code_warning: "እባክዎን ኮድዎን በደህንነት ያስቀምጡ። ወደ MIZAN መለያዎ ለመግባት ያስፈልግዎታል።",
    link_genius_title: "ብልህን ያገናኙ",
    link_genius_desc: "በተማሪው የቀረበውን የብልህ ኮድ ያስገቡ።",
    genius_code_label: "የብልህ ኮድ",
    genius_code_placeholder: "ምሳሌ: ANZ-982143",
    link_genius_button: "ብልህ አገናኝ",
    registration_failed: "ምዝገባ ሊጠናቀቅ አልቻለም።",
    server_error: "ምዝገባዎን ማጠናቀቅ አልቻልንም። እባክዎን እንደገና ይሞክሩ።",
    required_field: "ይህ መስክ ያስፈልጋል።",
    invalid_name: "እባክዎን ትክክለኛ ስም ያስገቡ።",
    invalid_english_name: "እባክዎን ትክክለኛ ዓለም አቀፍ ስም በእንግሊዝኛ ያስገቡ።",
    country_required: "እባክዎን ሀገርዎን ይምረጡ።",
    role_required: "እባክዎን የመለያ አይነት ይምረጡ።",
    entity_required: "እባክዎን የድርጅትዎን መረጃ ያስገቡ።",
    branch_required: "እባክዎን ቅርንጫፍ ይምረጡ።",
    code_invalid: "ኮዱ ልክ ያልሆነ ነው።",
    code_not_found: "ኮዱ አልተገኘም።",
    code_already_used: "ይህ ኮድ ቀድሞ ጥቅም ላይ ውሏል።",
    network_error: "የግንኙነት ስህተት ተከስቷል። እባክዎን እንደገና ይሞክሩ።",
    back_button: "ተመለስ",
    continue_button: "ቀጥል",
    cancel_button: "ሰርዝ",
    change_account_type: "የመለያ አይነት ይቀይሩ",
    switch_account: "መለያ ይቀይሩ",
    language_label: "ቋንቋ",
    change_language: "ቋንቋ ይቀይሩ",
    language_saved: "የቋንቋ ምርጫ ተቀምጧል።",
    language_loading: "ቋንቋ በመጫን ላይ...",
    language_unavailable: "ይህ ቋንቋ ለጊዜው አይገኝም።",
    monthly_award_label: "የወሩ ተሰጥኦዎች",
    monthly_description: "የወሩ ተሰጥኦዎች",
    reports_label: "ሪፖርት ክፈት",
    cognitive_profile_label: "ትኩረት",
    entity_type_school: "ትምህርት ቤቶች",
    entity_type_academy: "አካዳሚዎች",
    entity_type_center: "ማእከላት",
    entity_type_institute: "ተቋማት",
    entity_type_club: "ክለቦች",
    entity_type_educational_institution: "የትምህርት ተቋም",
    entity_type_federation: "የድርጅት አይነት",
    entity_type_training_organization: "የድርጅት አይነት",
    entity_type_other: "ሌላ",
    organization_country: "ሀገር",
    organization_city: "ከተማ",
    branch_code: "ቅርንጫፍ — የድርጅት ኮድ",
    branch_name: "ቅርንጫፍ — የድርጅት ስም",
    branch_manager: "የቅርንጫፍ አስተዳዳሪ",
    international_name_privacy: "ይህ ስም በዓለም አቀፍ የመሪ ሰንጠረዦች፣ ውድድሮች እና ዓለም አቀፍ እውቅና ላይ ጥቅም ላይ ይውላል።",
    leaderboard_name_notice: "ይህ ስም በዓለም አቀፍ የመሪ ሰንጠረዦች፣ ውድድሮች እና ዓለም አቀፍ እውቅና ላይ ጥቅም ላይ ይውላል።",
    privacy_notice: "የእርስዎን ደህንነቱ የተጠበቀ MIZAN ማንነት ይፍጠሩ እና ወደ ግላዊ የመማሪያ ጉዞዎ ይቀጥሉ።"
};
