/* MIZAN ANZAN — Final Global Locale */
/* Language: az | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["az"] = {
    brand_title: "MIZAN ANZAN",
    meta_description: "Mizan Anzan — peşəkar Anzan və Soroban təlim platforması",
    language_selector_aria: "Dil seçimi",
    answer_placeholder: "Nəticəni buraya daxil edin",
    platform_subtitle: "İnsan İnkişafı üzrə Beynəlxalq Alimlər Komissiyasının platforması — Fransa",
    nav_setup: "Təlim Parametrləri",
    nav_leaderboard: "Reytinq (Top 20)",
    nav_trainer: "Məşqçi Portalı",
    nav_parent: "Valideyn Portalı",
    nav_monthly: "Ayın Dahiləri",
    nav_history: "Təlim Tarixi və Hesabatlar",
    student_code_label: "Dahi Kodu:",
    reset_account: "Qeydiyyat / Hesabı Dəyiş",
    preset_kyu_dan_label: "Məşqçi - Təlim Səviyyəsini Təyin Et",
    preset_custom: "-- Xüsusi Əl İlə Quraşdırma --",
    preset_kyu_beginner: "Başlanğıc Səviyyə (Kyu 10 - Kyu 7) | 1-2 Rəqəm - 3-5 Sətir",
    preset_kyu_inter: "Orta Səviyyə (Kyu 6 - Kyu 4) | 2-3 Rəqəm - 5-8 Sətir",
    preset_kyu_advanced: "İrəli Səviyyə (Kyu 3 - Kyu 1) | 3-5 Rəqəm - 8-12 Sətir",
    preset_dan_pro: "Peşəkar Səviyyə (Dan 1 - Dan 5) | 5-8 Rəqəm - 15-25 Sətir",
    preset_dan_master: "Usta Səviyyəsi (Dan 6 - Dan 10) | 8-10 Rəqəm - 30-50 Sətir",
    preset_olympiad_gm: "Dünya Olimpiadası Səviyyəsi (Qrosmeyster) | 10-15 Rəqəm - 50-100 Sətir",
    mode_label: "Təlim Rejimi",
    mode_flash: "Flash Anzan",
    mode_flash_desc: "Yüksək sürətli ardıcıl flaş",
    mode_standard: "Standart Soroban (Statik)",
    mode_standard_desc: "Tam statik nömrə displeyi",
    level_label: "Səviyyə (Ciddi Soroban Qaydaları)",
    level_l1: "L1 - Birbaşa Toplama/Çıxma (Tamamlayıcı yox)",
    level_l2: "L2 - 5-in Dostları (5 Tamamlayıcıları)",
    level_l3: "L3 - 10-un Dostları (10 Tamamlayıcıları)",
    level_lm: "LM - Hərtərəfli Qarışıq (Bütün Qaydalar)",
    age_label: "Yaş Qrupu",
    age_under_6: "6 yaşdan kiçik",
    age_7_9: "7 - 9 yaş",
    age_10_12: "10 - 12 yaş",
    age_13_15: "13 - 15 yaş",
    age_16_plus: "16+ yaş",
    digits_label: "Rəqəmlər",
    rows_label: "Sətirlər",
    op_label: "Əməliyyat Növü",
    op_add: "Yalnız Toplama",
    op_sub: "Yalnız Çıxma",
    op_mix: "Qarışıq (Toplama və Çıxma)",
    duration_label: "Çağırış Vaxtı (saniyə)",
    rest_label: "İstirahət Vaxtı",
    rest_1s: "1 Saniyə",
    rest_2s: "2 Saniyə",
    rest_3s: "3 Saniyə",
    rest_4s: "4 Saniyə",
    rest_5s: "5 Saniyə",
    speed_label: "Ekran Sürəti (saniyə)",
    tts_label: "Nömrə Tələffüzü",
    start_button: "Çağırışa Başla",
    timer_label: "Qalan Vaxt:",
    score_label: "Bal:",
    exit_button: "Çıx",
    submit_answer: "Cavabı Göndər",
    welcome_title: "Mizan Anzan-a Xoş Gəldiniz",
    welcome_desc: "İzləmə kodunuzu yaratmaq üçün məlumatlarınızı qeydiyyatdan keçirin",
    fullname_label: "Dahinin Tam Adı",
    fullname_ph: "Tam adınızı daxil edin",
    country_label: "Ölkə",
    country_ph: "Nümunə: Fransa, Misir, Səudiyyə Ərəbistanı",
    generate_code_btn: "Dahi Kodu Yarat və Daxil Ol",
    countdown_start: "BAŞLA!",
    generation_error: "Bu parametrlərlə etibarlı çağırış yaratmaq mümkün deyil.",
    correct_feedback: "Düzgün cavab! Əla iş, dahi.",
    incorrect_feedback: "Səhv. Düzgün cavab:",
    invalid_integer: "Zəhmət olmasa etibarlı tam ədəd daxil edin.",
    challenge_complete: "Çağırış Tamamlandı!",
    total_score: "Ümumi Bal:",
    correct_answers: "Düzgün Cavablar:",
    of_word: "dən",
    trainer_title: "Məşqçi İdarəetmə Paneli",
    parent_title: "Valideyn İrəliləyiş Paneli",
    portal_desc: "İrəliləyiş və ətraflı analiz görmək üçün dahi kodunu daxil edin",
    lookup_placeholder: "Dahi kodunu daxil edin (məs: ANZ-982143)",
    follow_up: "Bax",
    enter_code: "Zəhmət olmasa dahi kodunu daxil edin",
    tracked_student: "İzlənən dahi:",
    active_account: "Aktiv qeydiyyatdan keçmiş hesab",
    genius_fallback: "Anzan Dahisi",
    focus_metric: "Diqqət",
    accuracy_metric: "Dəqiqlik",
    perf_metric: "Performans və Sürət",
    growth_metric: "İnkişaf",
    th_rank: "#",
    th_code: "Kod",
    th_country: "Ölkə",
    th_name: "Dahi Adı",
    th_mode: "Rejim",
    th_age: "Yaş Qrupu",
    th_level: "Səviyyə",
    th_digits: "Rəqəmlər",
    th_rows: "Sətirlər",
    th_operation: "Əməliyyat",
    th_duration: "Müddət",
    th_speed: "Sürət",
    th_points: "Xallar",
    leaderboard_title: "Reytinq — Top 20",
    leaderboard_empty: "Hələ heç bir nəticə yoxdur.",
    mode_flash_short: "Flash Anzan",
    mode_standard_short: "Standart Soroban",
    op_add_short: "Toplama",
    op_sub_short: "Çıxma",
    op_mix_short: "Qarışıq",
    subtract_speech: "Çıxma",
    seconds_short: "sn",
    challenge_invalid: "Çağırış başlaya bilmədi. Parametrləri yoxlayın və yenidən cəhd edin.",
    challenge_generation_failed: "Çağırış yaratmaq mümkün olmadı. Test başlamadı. Zəhmət olmasa təlim parametrlərini yoxlayın.",
    save_failed: "Çağırış nəticəsi serverdə yadda saxlanıla bilmədi. Bu cəhd hesabatlarda və ya reytinqdə sayılmadı.",
    save_success: "Nəticə uğurla yadda saxlanıldı və tələbə kodu ilə əlaqələndirildi.",
    save_queued: "Server müvəqqəti olaraq əlçatan deyil. Bu cəhd yerli olaraq saxlanıldı və əlaqə bərpa edildikdə avtomatik sinxronizasiya olunacaq.",
    open_report_prompt: "Hesabatı indi açmaq istəyirsiniz?",
    loading_data: "Məlumat yüklənir...",
    monthly_failed: "Ayın dahiləri yüklənə bilmədi.",
    monthly_title: "Ayın Dahiləri",
    sessions_metric: "Sessiyalar",
    questions_metric: "Suallar",
    points_metric: "Xallar",
    streak_metric: "Ən Yaxşı Seriya",
    student_not_found: "Tələbə tapılmadı və ya məlumat yüklənə bilmədi.",
    result_title: "Çağırış Tamamlandı!",
    result_subtitle: "Çağırış nəticəniz nəzərdən keçirməyə hazırdır.",
    result_score: "Ümumi Bal:",
    result_correct: "Düzgün Cavablar:",
    result_saved: "Nəticə uğurla yadda saxlanıldı və tələbə kodu ilə əlaqələndirildi.",
    result_open_report: "Hesabatı Aç",
    result_continue: "Davam Et",
    version_label: "Soroban Core v3.1",
    registration_title: "MIZAN ANZAN-a xoş gəldiniz",
    registration_desc: "Təhlükəsiz MIZAN kimliyinizi yaradın və fərdiləşdirilmiş öyrənmə səyahətinizi davam etdirin.",
    registration_language_label: "Qeydiyyat dili",
    registration_language_desc: "MIZAN təcrübəniz boyunca istifadə etmək istədiyiniz dili seçin.",
    role_selection_title: "Hesab növünüzü seçin",
    role_selection_desc: "MIZAN-ı necə istifadə edəcəyinizi ən yaxşı təsvir edən hesab növünü seçin.",
    role_genius: "Dahi",
    role_genius_desc: "Təlim keçmək, inkişaf etmək və öz irəliləyişini izləmək istəyən öyrənənlər üçün.",
    role_coach: "Məşqçi",
    role_coach_desc: "Təlim, hazırlıq və tələbə irəliləyişini idarə edən məşqçilər üçün.",
    role_parent: "Valideyn",
    role_parent_desc: "Övladının irəliləyişini izləmək istəyən valideynlər və ya qəyyumlar üçün.",
    role_entity: "Təşkilat",
    role_entity_desc: "Məktəblər, akademiyalar, mərkəzlər, institutlar, klublar, federasiyalar və təlim təşkilatları üçün.",
    genius_full_name_label: "Dahinin Tam Adı",
    genius_full_name_placeholder: "Tam adınızı daxil edin",
    display_name_en_label: "İngiliscə Beynəlxalq Ad",
    display_name_en_placeholder: "Adınızı ingiliscə daxil edin",
    display_name_en_help: "Bu ad beynəlxalq liderlik cədvəllərində, yarışlarda və qlobal tanınmada istifadə olunacaq.",
    display_name_en_required: "Beynəlxalq ingilis adınız tələb olunur.",
    display_name_en_invalid: "Xahiş edirik ingilis hərflərindən istifadə edərək etibarlı beynəlxalq ad daxil edin.",
    display_name_en_confirm: "Təsdiq edirəm ki, bu beynəlxalq səviyyədə istifadə etmək istədiyim ingilis adıdır.",
    country_placeholder: "Ölkənizi seçin",
    country_search_placeholder: "Ölkənizi axtarın",
    country_help: "Ölkəniz beynəlxalq sıralama və yarışlar üçün istifadə olunacaq.",
    entity_name_label: "Təşkilatın Adı",
    entity_name_placeholder: "Təşkilatın adını daxil edin",
    entity_type_label: "Təşkilat Növü",
    branch_label: "Filial",
    branch_placeholder: "Bir filial seçin",
    branch_optional: "Filial seçimi isteğe bağlıdır",
    branch_main: "Əsas Təşkilat",
    independent_coach: "Müstəqil Məşqçi",
    independent_coach_title: "Müstəqil Məşqçi",
    independent_coach_desc: "Heç bir təşkilata qoşulmadan müstəqil məşqçi kimi qeydiyyatdan keçin.",
    independent_coach_note: "Müstəqil məşqçilər təşkilat və ya filial olmadan qeydiyyatdan keçə bilərlər.",
    coach_registration_title: "Məşqçi Qeydiyyatı",
    coach_registration_desc: "Peşəkar MIZAN Məşqçi hesabınızı yaradın.",
    coach_code_label: "Məşqçi Kodu",
    parent_registration_title: "Valideyn Qeydiyyatı",
    parent_registration_desc: "Təhlükəsiz valideyn və ya qəyyum hesabınızı yaradın.",
    parent_code_label: "Valideyn Kodu",
    entity_code_label: "Təşkilat Kodu",
    entity_code_placeholder: "Təşkilat Kodunuzu daxil edin",
    entity_code_help: "Təşkilatınızın MIZAN hesabına daxil olmaq üçün bu kodu istifadə edin.",
    create_account_button: "Hesab Yarat",
    create_genius_account_button: "Dahi Hesabı Yarat",
    create_coach_account_button: "Məşqçi Hesabı Yarat",
    create_parent_account_button: "Valideyn Hesabı Yarat",
    create_organization_account_button: "Təşkilat Hesabı Yarat",
    registration_success_title: "Qeydiyyat Uğurlu Oldu",
    registration_success_desc: "MIZAN hesabınız uğurla yaradıldı.",
    your_genius_code: "Dahi Kodunuz",
    your_coach_code: "Məşqçi Kodunuz",
    your_parent_code: "Valideyn Kodunuz",
    your_organization_code: "Təşkilat Kodunuz",
    save_code_warning: "Xahiş edirik kodunuzu təhlükəsiz şəkildə saxlayın. MIZAN hesabınıza daxil olmaq üçün ona ehtiyacınız olacaq.",
    link_genius_title: "Bir Dahini Bağla",
    link_genius_desc: "Öyrənən tərəfindən təqdim olunan Dahi Kodunu daxil edin.",
    genius_code_label: "Dahi Kodu",
    genius_code_placeholder: "Nümunə: ANZ-982143",
    link_genius_button: "Dahini Bağla",
    registration_failed: "Qeydiyyat tamamlana bilmədi.",
    server_error: "Qeydiyyatınızı tamamlaya bilmədik. Xahiş edirik yenidən cəhd edin.",
    required_field: "Bu sahə tələb olunur.",
    invalid_name: "Xahiş edirik etibarlı ad daxil edin.",
    invalid_english_name: "Xahiş edirik ingiliscə etibarlı beynəlxalq ad daxil edin.",
    country_required: "Xahiş edirik ölkənizi seçin.",
    role_required: "Xahiş edirik hesab növü seçin.",
    entity_required: "Xahiş edirik təşkilat məlumatlarınızı daxil edin.",
    branch_required: "Xahiş edirik bir filial seçin.",
    code_invalid: "Kod etibarsızdır.",
    code_not_found: "Kod tapılmadı.",
    code_already_used: "Bu kod artıq istifadə olunur.",
    network_error: "Əlaqə xətası baş verdi. Xahiş edirik yenidən cəhd edin.",
    back_button: "Geri",
    continue_button: "Davam Et",
    cancel_button: "Ləğv Et",
    change_account_type: "Hesab Növünü Dəyiş",
    switch_account: "Hesabı Dəyiş",
    language_label: "Dil",
    change_language: "Dili Dəyiş",
    language_saved: "Dil seçimi saxlanıldı.",
    language_loading: "Dil yüklənir...",
    language_unavailable: "Bu dil müvəqqəti olaraq əlçatan deyil.",
    monthly_award_label: "Ayın Dahiləri",
    monthly_description: "Ayın Dahiləri",
    reports_label: "Hesabatı Aç",
    cognitive_profile_label: "Diqqət",
    entity_type_school: "Məktəblər",
    entity_type_academy: "akademiyalar",
    entity_type_center: "mərkəzlər",
    entity_type_institute: "institutlar",
    entity_type_club: "klublar",
    entity_type_educational_institution: "Təhsil Müəssisəsi",
    entity_type_federation: "Təşkilat Növü",
    entity_type_training_organization: "Təşkilat Növü",
    entity_type_other: "Digər",
    organization_country: "Ölkə",
    organization_city: "Şəhər",
    branch_code: "Filial — Təşkilat Kodu",
    branch_name: "Filial — Təşkilatın Adı",
    branch_manager: "Filial meneceri",
    international_name_privacy: "Bu ad beynəlxalq liderlik cədvəllərində, yarışlarda və qlobal tanınmada istifadə olunacaq.",
    leaderboard_name_notice: "Bu ad beynəlxalq liderlik cədvəllərində, yarışlarda və qlobal tanınmada istifadə olunacaq.",
    privacy_notice: "Təhlükəsiz MIZAN kimliyinizi yaradın və fərdiləşdirilmiş öyrənmə səyahətinizi davam etdirin."
};
