/* MIZAN ANZAN — Final Global Locale */
/* Language: ber | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["ber"] = {
    brand_title: "MIZAN ANZAN",
    meta_description: "Mizan Anzan — asaram n uẓṛu n Anzan d Soroban",
    language_selector_aria: "Fren tameslayt",
    answer_placeholder: "Aru agmuḍ da",
    platform_subtitle: "Asaram n Tnbadit Tagrartant n Imusnawen i Tneflit n Umdan — Fransa",
    nav_setup: "Iγewwaṛen n uẓṛu",
    nav_leaderboard: "Tabdart n imeqqranen (Top 20)",
    nav_trainer: "Taburt n umɛallem",
    nav_parent: "Taburt n imawlan",
    nav_monthly: "Iɛeqqalen n wayyur",
    nav_history: "Amzruy n uẓṛu d iṭerfiyen",
    student_code_label: "Tangalt n uɛeqqal:",
    reset_account: "Aderrej / Bddel amedya",
    preset_kyu_dan_label: "Amɛallem - Sken aswir n uẓṛu",
    preset_custom: "-- Askar afuskan yettwafen --",
    preset_kyu_beginner: "Aswir amezwaru (Kyu 10 - Kyu 7) | 1-2 n yidraren - 3-5 n yisurifen",
    preset_kyu_inter: "Aswir anammas (Kyu 6 - Kyu 4) | 2-3 n yidraren - 5-8 n yisurifen",
    preset_kyu_advanced: "Aswir alemmas (Kyu 3 - Kyu 1) | 3-5 n yidraren - 8-12 n yisurifen",
    preset_dan_pro: "Aswir ameɣlaf (Dan 1 - Dan 5) | 5-8 n yidraren - 15-25 n yisurifen",
    preset_dan_master: "Aswir n umasṭer (Dan 6 - Dan 10) | 8-10 n yidraren - 30-50 n yisurifen",
    preset_olympiad_gm: "Aswir n Olimpiad n Umaḍal (Grandmaster) | 10-15 n yidraren - 50-100 n yisurifen",
    mode_label: "Anaw n uẓṛu",
    mode_flash: "Anzan afriw",
    mode_flash_desc: "Askar n tafriwin tifawin",
    mode_standard: "Soroban amezgi (Agdim)",
    mode_standard_desc: "Askar n yidraren igdimen",
    level_label: "Aswir (Ilelli n Soroban iǧehden)",
    level_l1: "L1 - Asget/Asenzi uggar (war tmerniyin)",
    level_l2: "L2 - Imeddukal n 5 (tmerniyin n 5)",
    level_l3: "L3 - Imeddukal n 10 (tmerniyin n 10)",
    level_lm: "LM - Yemxalluṭ yettwassen (Akk ilelli)",
    age_label: "Agraw n wessawen",
    age_under_6: "D awezri n 6 iseggwasen",
    age_7_9: "7 - 9 iseggwasen",
    age_10_12: "10 - 12 iseggwasen",
    age_13_15: "13 - 15 iseggwasen",
    age_16_plus: "16+ iseggwasen",
    digits_label: "Idraren",
    rows_label: "Isurifen",
    op_label: "Anaw n tuwuri",
    op_add: "Asget kan",
    op_sub: "Asenzi kan",
    op_mix: "Yemxalluṭ (asget d usenzi)",
    duration_label: "Lweqt n unqis (tasdidt)",
    rest_label: "Lweqt n urayeḥ",
    rest_1s: "1 tasdidt",
    rest_2s: "2 tasdidin",
    rest_3s: "3 tasdidin",
    rest_4s: "4 tasdidin",
    rest_5s: "5 tasdidin",
    speed_label: "Tazzla n uskar (tasdidin)",
    tts_label: "Ameslay n yidraren",
    start_button: "Bdu anqis",
    timer_label: "Lweqt i d-yeqqimen:",
    score_label: "Tigzi:",
    exit_button: "Ffeɣ",
    submit_answer: "Azen tiririt",
    welcome_title: "Ansuf ɣer Mizan Anzan",
    welcome_desc: "Err talɣut inek akken ad tesked asedday n tɣawsa",
    fullname_label: "Isem ufessas n uɛeqqal",
    fullname_ph: "Aru isem ik ufessas",
    country_label: "ⴰⵎⵓⵔ",
    country_ph: "Amdya: Fransa, Maṣer, Suɛudiya",
    generate_code_btn: "Sked tangalt n uɛeqqal sseddu",
    countdown_start: "Bdu!",
    generation_error: "Ur yezmir ara ad isked anqis yelhan s yigewwaṛen agi.",
    correct_feedback: "Tiririt telha! Lḥemdu l-ṛebbi, aɛeqqal.",
    incorrect_feedback: "Tiririt teḍra. Tiririt telha tella:",
    invalid_integer: "Err amḍan ameḍqan.",
    challenge_complete: "Anqis yemmed!",
    total_score: "Agmuḍ n tigzi:",
    correct_answers: "Tiriritin tiwulayin:",
    of_word: "si",
    trainer_title: "Aɣerbaz n umɛallem",
    parent_title: "Aɣerbaz n uẓri n imawlan",
    portal_desc: "Err tangalt n uɛeqqal akken ad twaliḍ aswir d tafelwit",
    lookup_placeholder: "Err tangalt n uɛeqqal (am: ANZ-982143)",
    follow_up: "Sken",
    enter_code: "Err tangalt n uɛeqqal",
    tracked_student: "Aɛeqqal i d-yettwaḍfar:",
    active_account: "Amedya yettwaderres yettwaxeddem",
    genius_fallback: "Aɛeqqal n Anzan",
    focus_metric: "Tawjja",
    accuracy_metric: "Tidett",
    perf_metric: "Tuwuri d tazzla",
    growth_metric: "Tlelli",
    th_rank: "#",
    th_code: "Tangalt",
    th_country: "Tamurt",
    th_name: "Isem n uɛeqqal",
    th_mode: "Anaw",
    th_age: "Agraw n wessawen",
    th_level: "Aswir",
    th_digits: "Idraren",
    th_rows: "Isurifen",
    th_operation: "Tuwuri",
    th_duration: "Lweqt",
    th_speed: "Tazzla",
    th_points: "Tiqziwin",
    leaderboard_title: "Tabdart imeqqranen — Top 20",
    leaderboard_empty: "Ur illi ula d yiwen n ugmuḍ.",
    mode_flash_short: "Anzan afriw",
    mode_standard_short: "Soroban amezgi",
    op_add_short: "Asget",
    op_sub_short: "Asenzi",
    op_mix_short: "Yemxalluṭ",
    subtract_speech: "Asenzi",
    seconds_short: "s",
    challenge_invalid: "Ur yezmir ara ad ibdu anqis. Sken iγewwaṛen ɛawed.",
    challenge_generation_failed: "Ur yezmir ara ad isked anqis. Tajarribt ur tebdu. Sken iγewwaṛen n uẓṛu.",
    save_failed: "Ur yezmir ara ad isekles agmuḍ n unqis ɣef uqeddac. Tajribt-agi ur tepḥisab ara di trebbut n iṭerfiyen neɣ tabdart.",
    save_success: "Agmuḍ yettwasekles yelha yettwaqqen d tangalt n unelmad.",
    save_queued: "Aqeddac ur yelli ara d awezri. Tajribt-agi tettwasekles ɣef ugani, ahat tettwasegza ticki ara d-yuɣal uddis.",
    open_report_prompt: "Tebɣiḍ ad teftḥ aṭerfi aman?",
    loading_data: "Askar n yisaffen...",
    monthly_failed: "Ur iwumi ara ad yeskecmed iɛeqqalen n wayyur.",
    monthly_title: "Iɛeqqalen n wayyur",
    sessions_metric: "Tiɣuriwin",
    questions_metric: "Isteqsiyen",
    points_metric: "Tiqziwin",
    streak_metric: "Ahil ameqran",
    student_not_found: "Unelmad ur yettwaf ara neɣ isaffen ur d-usan.",
    result_title: "Anqis yemmed!",
    result_subtitle: "Agmuḍ n unqis inek iɛeḍḍa i tẓaṛt.",
    result_score: "Agmuḍ n tigzi:",
    result_correct: "Tiriritin tiwulayin:",
    result_saved: "Agmuḍ yettwasekles yelha yettwaqqen d tangalt n unelmad.",
    result_open_report: "Fteḥ aṭerfi",
    result_continue: "Kemmel",
    version_label: "Soroban Core v3.1",
    registration_title: "ⴰⵏⵙⴰⴼⵓ ⵖⵔ MIZAN ANZAN",
    registration_desc: "ⵙⵏⴼⵍ ⵓⵙⵔⵉⴷ ⵏⵏⴽ ⵉⵣⵣⴷⵉⵏ ⴳ MIZAN ⵓⵔⴰⵔ ⴰⵎⴰⵔⴰⵢ ⵏ ⵜⵍⵎⵉⴷⵜ ⵏⵏⴽ.",
    registration_language_label: "ⵜⵓⵜⵍⴰⵢⵜ ⵏ ⵓⵙⴳⴷ",
    registration_language_desc: "ⴼⵔⵓⵙ ⵜⵓⵜⵍⴰⵢⵜ ⵏⵏⴰ ⵜⵔⵉⵔⵉⵜ ⴰⴷ ⵜⵙⵙⵎⵔⵙⴷ ⴳ ⵓⵎⴰⵔⴰⵢ ⵏⵏⴽ ⴳ MIZAN.",
    role_selection_title: "ⴼⵔⵓⵙ ⴰⵏⴰⵡ ⵏ ⵓⵎⵉⴹⴰⵏ ⵏⵏⴽ",
    role_selection_desc: "ⴼⵔⵓⵙ ⴰⵏⴰⵡ ⵏ ⵓⵎⵉⴹⴰⵏ ⴰⵔ ⵉⵙⵎⴰⵜⵜⴰⵢ ⴰⴽⴽ ⴰⵎⴷⵢⴰ ⵏ ⵎⴰⵎⴽ ⴰⵔ ⵜⵙⵙⵎⵔⵙⴷ MIZAN.",
    role_genius: "ⴰⵎⵏⵣⴰⵀ",
    role_genius_desc: "ⵉ ⵉⵎⵔⴰⵔⵏ ⵉⵔⴰⵏ ⴰⴷ ⵎⵔⴰⵔⵏ, ⴰⴷ ⵙⵙⵏⴼⵍⵏ ⴷ ⴰⴷ ⴷⴰⵔⵉⵏ ⴰⵎⵓⵙⵙⵓ ⵏⵏⵙⵏ.",
    role_coach: "ⴰⵎⴳⵏⵣⵉ",
    role_coach_desc: "ⵉ ⵉⵎⴳⵏⵣⵉⵢⵏ ⴰⵔ ⵙⵡⵓⵔⵉⵏ ⴳ ⵓⵙⵍⵎⴰⴷ, ⴰⵎⵔⴰⵔ ⴷ ⵓⵎⵓⵙⵙⵓ ⵏ ⵉⵎⵔⴰⵔⵏ.",
    role_parent: "ⴰⴱⴰⴱⴰⵣ",
    role_parent_desc: "ⵉ ⵉⴱⴰⴱⴰⵣⵏ ⵏⵖ ⵉⵎⵏⵣⴰⵔⵏ ⵉⵔⴰⵏ ⴰⴷ ⴷⴰⵔⵉⵏ ⴰⵎⵓⵙⵙⵓ ⵏ ⵓⵔⵔⵓ ⵏⵏⵙⵏ.",
    role_entity: "ⵜⴰⵎⵔⵙⵍⵜ",
    role_entity_desc: "ⵉ ⵜⵉⵙⵓⵔⴰⵔⵉⵏ, ⵜⵉⴽⴰⴷⵉⵎⵢⴰⵢⵉⵏ, ⵉⵎⴰⵔⴰⵢⵏ, ⵉⵙⵉⵏⴰⵏ, ⵉⵎⴰⵔⴰⵢⵏ ⵏ ⵓⵎⵔⴰⵔ, ⵉⴼⴷⵉⵔⴰⵙⵢⵓⵏⵏ ⴷ ⵜⵎⵔⵙⴰⵍ ⵏ ⵓⵎⵔⴰⵔ.",
    genius_full_name_label: "ⵉⵙⴻⵎ ⴰⵛⴰⵔ ⵏ ⵓⵎⵏⵣⴰⵀ",
    genius_full_name_placeholder: "ⵙⴽⵛⴰ ⵉⵙⴻⵎ ⴰⵛⴰⵔ ⵏⵏⴽ",
    display_name_en_label: "ⴰⵙⵙⴰⵖ ⴰⴳⵔⴰⵖⵍⴰⵏ ⵙ ⵜⵏⴳⵍⵉⵣⵉⵜ",
    display_name_en_placeholder: "ⵙⴽⵛⴰ ⵉⵙⴻⵎ ⵏⵏⴽ ⵙ ⵜⵏⴳⵍⵉⵣⵉⵜ",
    display_name_en_help: "ⴰⴷ ⵉⵙⵙⵎⵔⵙ ⵓⵙⵙⴰⵖ ⴰⴷ ⴳ ⵡⴰⵏⴰⵢⵏ ⴰⴳⵔⴰⵖⵍⴰⵏⵏ, ⵜⵉⵎⵣⴰⵔⴰⵢⵉⵏ ⴷ ⵓⵙⵙⵏⵜⵉ ⴰⵎⴰⴹⵍⴰⵏ.",
    display_name_en_required: "ⴰⵙⵙⴰⵖ ⵏⵏⴽ ⴰⴳⵔⴰⵖⵍⴰⵏ ⵙ ⵜⵏⴳⵍⵉⵣⵉⵜ ⵉⵜⵜⵓⵖⵙⵏ.",
    display_name_en_invalid: "ⵙⴽⵛⴰ ⴰⵙⵙⴰⵖ ⴰⴳⵔⴰⵖⵍⴰⵏ ⵉⵣⴷⵉⵏ ⵙ ⵉⵙⴽⴽⵉⵍⵏ ⵏ ⵜⵏⴳⵍⵉⵣⵉⵜ.",
    display_name_en_confirm: "ⴰⴷ ⵙⵙⵏⵜⴰⵖ ⴰⵏⵏⴰ ⵎⴰⵙⴷ ⵓⵏⴰ ⵉⵙⴻⵎ ⵙ ⵜⵏⴳⵍⵉⵣⵉⵜ ⵉⵔⵉⵔⵉⵖ ⴰⴷ ⵜⵙⵙⵎⵔⵙⵖ ⴳ ⵓⴳⵔⴰⵖⵍⴰⵏ.",
    country_placeholder: "ⴼⵔⵓⵙ ⴰⵎⵓⵔ ⵏⵏⴽ",
    country_search_placeholder: "ⵔⵣⵓ ⴰⵎⵓⵔ ⵏⵏⴽ",
    country_help: "ⴰⴷ ⵉⵙⵙⵎⵔⵙ ⵓⵎⵓⵔ ⵏⵏⴽ ⵉ ⵓⵙⵔⵜⴰⵏ ⴷ ⵜⵎⵣⴰⵔⴰⵢⵉⵏ ⵜⵉⴳⵔⴰⵖⵍⴰⵏⵉⵏ.",
    entity_name_label: "ⵉⵙⴻⵎ ⵏ ⵜⵎⵔⵙⵍⵜ",
    entity_name_placeholder: "ⵙⴽⵛⴰ ⵉⵙⴻⵎ ⵏ ⵜⵎⵔⵙⵍⵜ",
    entity_type_label: "ⴰⵏⴰⵡ ⵏ ⵜⵎⵔⵙⵍⵜ",
    branch_label: "ⵜⴰⵙⴷⴰⵡⵜ",
    branch_placeholder: "ⴼⵔⵓⵙ ⵜⴰⵙⴷⴰⵡⵜ",
    branch_optional: "ⵓⵔ ⵉⵍⵍⵉ ⵓⵖⵉⵍ ⴳ ⵓⴼⵔⵓⵙ ⵏ ⵜⵙⴷⴰⵡⵜ",
    branch_main: "ⵜⴰⵎⵔⵙⵍⵜ ⵜⴰⵏⴰⴼⵍⴰⵢⵜ",
    independent_coach: "ⴰⵎⴳⵏⵣⵉ ⴰⵣⴰⵔⴰⴳ",
    independent_coach_title: "ⴰⵎⴳⵏⵣⵉ ⴰⵣⴰⵔⴰⴳ",
    independent_coach_desc: "ⴰⵙⴳⴷ ⵢⴰⵍ ⵓⵎⴳⵏⵣⵉ ⴰⵣⴰⵔⴰⴳ ⴱⵍⴰ ⴰⴷ ⵜⵉⵏⵉⴷ ⵉ ⵜⵎⵔⵙⵍⵜ.",
    independent_coach_note: "ⵉⵎⴳⵏⵣⵉⵢⵏ ⵉⵣⴰⵔⴰⴳⵏ ⵣⵎⵔⵏ ⴰⴷ ⴰⵙⴳⴷⵏ ⴱⵍⴰ ⵜⵎⵔⵙⵍⵜ ⵏⵖ ⵜⴰⵙⴷⴰⵡⵜ.",
    coach_registration_title: "ⴰⵙⴳⴷ ⵏ ⵓⵎⴳⵏⵣⵉ",
    coach_registration_desc: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ ⵏⵏⴽ ⴰⵎⵣⵣⵉⴰⵏ ⵏ ⵓⵎⴳⵏⵣⵉ ⴳ MIZAN.",
    coach_code_label: "ⵓⵣⵣⵔ ⵏ ⵓⵎⴳⵏⵣⵉ",
    parent_registration_title: "ⴰⵙⴳⴷ ⵏ ⵓⴱⴰⴱⴰⵣ",
    parent_registration_desc: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ ⵏⵏⴽ ⴰⵣⵣⴷⵉⵏ ⵏ ⵓⴱⴰⴱⴰⵣ ⵏⵖ ⵓⵎⵏⵣⴰⵔ.",
    parent_code_label: "ⵓⵣⵣⵔ ⵏ ⵓⴱⴰⴱⴰⵣ",
    entity_code_label: "ⵓⵣⵣⵔ ⵏ ⵜⵎⵔⵙⵍⵜ",
    entity_code_placeholder: "ⵙⴽⵛⴰ ⵓⵣⵣⵔ ⵏ ⵜⵎⵔⵙⵍⵜ ⵏⵏⴽ",
    entity_code_help: "ⵙⵙⵎⵔⵙ ⴰⵣⵣⵔ ⴰⴷ ⵉ ⵓⴷⵓⴼⵔ ⵖⵔ ⵓⵎⵉⴹⴰⵏ MIZAN ⵏ ⵜⵎⵔⵙⵍⵜ ⵏⵏⴽ.",
    create_account_button: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ",
    create_genius_account_button: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ ⵏ ⵓⵎⵏⵣⴰⵀ",
    create_coach_account_button: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ ⵏ ⵓⵎⴳⵏⵣⵉ",
    create_parent_account_button: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ ⵏ ⵓⴱⴰⴱⴰⵣ",
    create_organization_account_button: "ⵙⵏⴼⵍ ⴰⵎⵉⴹⴰⵏ ⵏ ⵜⵎⵔⵙⵍⵜ",
    registration_success_title: "ⴰⵙⴳⴷ ⵢⵓⵔⵉ",
    registration_success_desc: "ⴰⵎⵉⴹⴰⵏ ⵏⵏⴽ ⴳ MIZAN ⵉⵙⵏⴼⵍ ⵙ ⵓⵏⴰⴼⵍⴰ.",
    your_genius_code: "ⴰⵣⵣⵔ ⵏ ⵓⵎⵏⵣⴰⵀ ⵏⵏⴽ",
    your_coach_code: "ⴰⵣⵣⵔ ⵏ ⵓⵎⴳⵏⵣⵉ ⵏⵏⴽ",
    your_parent_code: "ⴰⵣⵣⵔ ⵏ ⵓⴱⴰⴱⴰⵣ ⵏⵏⴽ",
    your_organization_code: "ⴰⵣⵣⵔ ⵏ ⵜⵎⵔⵙⵍⵜ ⵏⵏⴽ",
    save_code_warning: "ⵙⵎⵉⴹ ⴰⵣⵣⵔ ⵏⵏⴽ ⵙ ⵓⵎⵏⵏⵉ. ⴰⴷ ⵜⵖⵙⴷ ⵙⵙⵏ ⵉ ⵓⴷⵓⴼⵔ ⵖⵔ ⵓⵎⵉⴹⴰⵏ ⵏⵏⴽ ⴳ MIZAN.",
    link_genius_title: "ⵇⵇⵏ ⴰⵎⵏⵣⴰⵀ",
    link_genius_desc: "ⵙⴽⵛⴰ ⴰⵣⵣⵔ ⵏ ⵓⵎⵏⵣⴰⵀ ⵉⵙⵙⵓⴼⵖ ⵓⵎⵔⴰⵔ.",
    genius_code_label: "ⴰⵣⵣⵔ ⵏ ⵓⵎⵏⵣⴰⵀ",
    genius_code_placeholder: "ⴰⵎⴷⵢⴰ: ANZ-982143",
    link_genius_button: "ⵇⵇⵏ ⴰⵎⵏⵣⴰⵀ",
    registration_failed: "ⵓⵔ ⵉⵜⵉⵔⵉ ⵓⵙⴳⴷ.",
    server_error: "ⵓⵔ ⵏⵣⵎⵔ ⴰⴷ ⵏⵙⴳⴷ ⴰⵙⴳⴷ ⵏⵏⴽ. ⵙⴰⵢⵏ ⵜⵉⵢⴰⴷ.",
    required_field: "ⴰⴷⵖⴰⵔ ⴰⴷ ⵉⵜⵜⵓⵖⵙⵏ.",
    invalid_name: "ⵙⴽⵛⴰ ⵉⵙⴻⵎ ⵉⵣⴷⵉⵏ.",
    invalid_english_name: "ⵙⴽⵛⴰ ⵉⵙⴻⵎ ⴰⴳⵔⴰⵖⵍⴰⵏ ⵉⵣⴷⵉⵏ ⵙ ⵜⵏⴳⵍⵉⵣⵉⵜ.",
    country_required: "ⴼⵔⵓⵙ ⴰⵎⵓⵔ ⵏⵏⴽ.",
    role_required: "ⴼⵔⵓⵙ ⴰⵏⴰⵡ ⵏ ⵓⵎⵉⴹⴰⵏ.",
    entity_required: "ⵙⴽⵛⴰ ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵜⵎⵔⵙⵍⵜ ⵏⵏⴽ.",
    branch_required: "ⴼⵔⵓⵙ ⵜⴰⵙⴷⴰⵡⵜ.",
    code_invalid: "ⵓⵣⵣⵔ ⵓⵔ ⵉⵣⴷⵉ.",
    code_not_found: "ⵓⵔ ⵉⵜⵜⵓⴼⴰ ⵓⵣⵣⵔ.",
    code_already_used: "ⴰⵣⵣⵔ ⴰⴷ ⵉⵜⵜⵓⵙⵎⵔⵙ ⵢⴰⴷ.",
    network_error: "ⵉⵡⴰⵔ ⵓⵣⵣⵔⵉⴽ ⵏ ⵓⵣⴰⵣⵓ. ⵙⴰⵢⵏ ⵜⵉⵢⴰⴷ.",
    back_button: "ⴰⵎⵣⵉⵔⵓ",
    continue_button: "ⵙⵉⵡⵉ",
    cancel_button: "ⵙⴽⵙ",
    change_account_type: "ⴱⴷⴷⵍ ⴰⵏⴰⵡ ⵏ ⵓⵎⵉⴹⴰⵏ",
    switch_account: "ⴱⴷⴷⵍ ⴰⵎⵉⴹⴰⵏ",
    language_label: "ⵜⵓⵜⵍⴰⵢⵜ",
    change_language: "ⴱⴷⴷⵍ ⵜⵓⵜⵍⴰⵢⵜ",
    language_saved: "ⵜⵓⵜⵍⴰⵢⵜ ⵉⵜⵜⵓⵙⵎⵉⴹⵏ.",
    language_loading: "ⴰⵙⵙⴰⵍⵍ ⵏ ⵜⵓⵜⵍⴰⵢⵜ...",
    language_unavailable: "ⵜⵓⵜⵍⴰⵢⵜ ⴰⴷ ⵓⵔ ⵜⵍⵍⵉ ⵖⵉⵍⴰ.",
    monthly_award_label: "Iɛeqqalen n wayyur",
    monthly_description: "Iɛeqqalen n wayyur",
    reports_label: "Fteḥ aṭerfi",
    cognitive_profile_label: "Tawjja",
    entity_type_school: "ⵜⵉⵙⵓⵔⴰⵔⵉⵏ",
    entity_type_academy: "ⵜⵉⴽⴰⴷⵉⵎⵢⴰⵢⵉⵏ",
    entity_type_center: "ⴰⵎⴰⵔⴰⵢ ⵏ ⵓⵎⵔⴰⵔ",
    entity_type_institute: "ⵉⵙⵉⵏⴰⵏ",
    entity_type_club: "ⴰⵎⴰⵔⴰ",
    entity_type_educational_institution: "ⵜⴰⵙⵏⵉⵍⵜ ⵏ ⵓⵙⵍⵎⴷ",
    entity_type_federation: "ⴰⴼⴷⵉⵔⴰⵙ",
    entity_type_training_organization: "ⵜⴰⵎⵔⵙⵍⵜ ⵏ ⵓⵎⵔⴰⵔ",
    entity_type_other: "ⵡⴰⵢⴻⴹ",
    organization_country: "ⴰⵎⵓⵔ",
    organization_city: "ⵜⴰⵎⴷⵉⵏⵜ",
    branch_code: "ⵜⴰⵙⴷⴰⵡⵜ — ⵓⵣⵣⵔ ⵏ ⵜⵎⵔⵙⵍⵜ",
    branch_name: "ⵜⴰⵙⴷⴰⵡⵜ — ⵉⵙⴻⵎ ⵏ ⵜⵎⵔⵙⵍⵜ",
    branch_manager: "ⴰⵎⵏⴰⵍ ⵏ ⵜⵙⴷⴰⵡⵜ",
    international_name_privacy: "ⴰⴷ ⵉⵙⵙⵎⵔⵙ ⵓⵙⵙⴰⵖ ⴰⴷ ⴳ ⵡⴰⵏⴰⵢⵏ ⴰⴳⵔⴰⵖⵍⴰⵏⵏ, ⵜⵉⵎⵣⴰⵔⴰⵢⵉⵏ ⴷ ⵓⵙⵙⵏⵜⵉ ⴰⵎⴰⴹⵍⴰⵏ.",
    leaderboard_name_notice: "ⴰⴷ ⵉⵙⵙⵎⵔⵙ ⵓⵙⵙⴰⵖ ⴰⴷ ⴳ ⵡⴰⵏⴰⵢⵏ ⴰⴳⵔⴰⵖⵍⴰⵏⵏ, ⵜⵉⵎⵣⴰⵔⴰⵢⵉⵏ ⴷ ⵓⵙⵙⵏⵜⵉ ⴰⵎⴰⴹⵍⴰⵏ.",
    privacy_notice: "ⵙⵏⴼⵍ ⵓⵙⵔⵉⴷ ⵏⵏⴽ ⵉⵣⵣⴷⵉⵏ ⴳ MIZAN ⵓⵔⴰⵔ ⴰⵎⴰⵔⴰⵢ ⵏ ⵜⵍⵎⵉⴷⵜ ⵏⵏⴽ."
};
