/* MIZAN ANZAN — Final Global Locale */
/* Language: bg | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["bg"] = {
    brand_title: "MIZAN ANZAN",
    meta_description: "Mizan Anzan — професионална платформа за обучение по Анзан и Соробан",
    language_selector_aria: "Избор на език",
    answer_placeholder: "Въведете резултата тук",
    platform_subtitle: "Платформа на Международната комисия на учените за човешко развитие — Франция",
    nav_setup: "Настройки на обучението",
    nav_leaderboard: "Класиране (Топ 20)",
    nav_trainer: "Портал на треньора",
    nav_parent: "Портал за родители",
    nav_monthly: "Гении на месеца",
    nav_history: "История на обучението и отчети",
    student_code_label: "Код на гений:",
    reset_account: "Регистрация / Смяна на профил",
    preset_kyu_dan_label: "Треньор - Задаване на ниво на обучение",
    preset_custom: "-- Персонализирана ръчна настройка --",
    preset_kyu_beginner: "Начално ниво (Kyu 10 - Kyu 7) | 1-2 цифри - 3-5 реда",
    preset_kyu_inter: "Средно ниво (Kyu 6 - Kyu 4) | 2-3 цифри - 5-8 реда",
    preset_kyu_advanced: "Напреднало ниво (Kyu 3 - Kyu 1) | 3-5 цифри - 8-12 реда",
    preset_dan_pro: "Професионално ниво (Dan 1 - Dan 5) | 5-8 цифри - 15-25 реда",
    preset_dan_master: "Мастър ниво (Dan 6 - Dan 10) | 8-10 цифри - 30-50 реда",
    preset_olympiad_gm: "Ниво Световна олимпиада (Гросмайстор) | 10-15 цифри - 50-100 реда",
    mode_label: "Режим на обучение",
    mode_flash: "Флаш Анзан",
    mode_flash_desc: "Високоскоростен последователен флаш",
    mode_standard: "Стандартен Соробан (Статичен)",
    mode_standard_desc: "Пълно показване на статични числа",
    level_label: "Ниво (Строги правила на Соробана)",
    level_l1: "L1 - Директно събиране/изваждане (Без допълнения)",
    level_l2: "L2 - Приятели на 5 (5 допълнения)",
    level_l3: "L3 - Приятели на 10 (10 допълнения)",
    level_lm: "LM - Изчерпателно смесено (Всички правила)",
    age_label: "Възрастова група",
    age_under_6: "Под 6 години",
    age_7_9: "7 - 9 години",
    age_10_12: "10 - 12 години",
    age_13_15: "13 - 15 години",
    age_16_plus: "16+ години",
    digits_label: "Цифри",
    rows_label: "Редове",
    op_label: "Тип операция",
    op_add: "Само събиране",
    op_sub: "Само изваждане",
    op_mix: "Смесено (Събиране и изваждане)",
    duration_label: "Време за предизвикателство (сек)",
    rest_label: "Време за почивка",
    rest_1s: "1 секунда",
    rest_2s: "2 секунди",
    rest_3s: "3 секунди",
    rest_4s: "4 секунди",
    rest_5s: "5 секунди",
    speed_label: "Скорост на показване (секунди)",
    tts_label: "Произношение на числа",
    start_button: "Стартиране на предизвикателството",
    timer_label: "Оставащо време:",
    score_label: "Резултат:",
    exit_button: "Изход",
    submit_answer: "Изпращане на отговор",
    welcome_title: "Добре дошли в Mizan Anzan",
    welcome_desc: "Моля, регистрирайте вашите данни, за да генерирате своя код за проследяване",
    fullname_label: "Пълно име на гения",
    fullname_ph: "Въведете вашето пълно име",
    country_label: "Държава",
    country_ph: "Пример: Франция, Египет, Саудитска Арабия",
    generate_code_btn: "Генериране на код на гений и влизане",
    countdown_start: "СТАРТ!",
    generation_error: "Не може да се генерира валидно предизвикателство с тези настройки.",
    correct_feedback: "Верен отговор! Отлична работа, гений.",
    incorrect_feedback: "Грешно. Верният отговор беше:",
    invalid_integer: "Моля, въведете валидно цяло число.",
    challenge_complete: "Предизвикателството е завършено!",
    total_score: "Общ резултат:",
    correct_answers: "Верни отговори:",
    of_word: "от",
    trainer_title: "Контролен панел на треньора",
    parent_title: "Панел за напредък на родителите",
    portal_desc: "Въведете кода на гений, за да видите напредъка и подробния анализ",
    lookup_placeholder: "Въведете код на гений (напр. ANZ-982143)",
    follow_up: "Преглед",
    enter_code: "Моля, въведете кода на гений",
    tracked_student: "Проследяван гений:",
    active_account: "Активен регистриран профил",
    genius_fallback: "Анзан Гений",
    focus_metric: "Фокус",
    accuracy_metric: "Точност",
    perf_metric: "Представяне и скорост",
    growth_metric: "Растеж",
    th_rank: "#",
    th_code: "Код",
    th_country: "Държава",
    th_name: "Име на гений",
    th_mode: "Режим",
    th_age: "Възрастова група",
    th_level: "Ниво",
    th_digits: "Цифри",
    th_rows: "Редове",
    th_operation: "Операция",
    th_duration: "Продължителност",
    th_speed: "Скорост",
    th_points: "Точки",
    leaderboard_title: "Класиране — Топ 20",
    leaderboard_empty: "Все още няма резултати.",
    mode_flash_short: "Флаш Анзан",
    mode_standard_short: "Стандартен Соробан",
    op_add_short: "Събиране",
    op_sub_short: "Изваждане",
    op_mix_short: "Смесено",
    subtract_speech: "Изваждане",
    seconds_short: "с",
    challenge_invalid: "Предизвикателството не можа да започне. Проверете настройките и опитайте отново.",
    challenge_generation_failed: "Предизвикателството не можа да бъде генерирано. Тестът не започна. Моля, проверете настройките за обучение.",
    save_failed: "Резултатът от предизвикателството не можа да бъде запазен на сървъра. Този опит не беше отчетен в отчетите или класирането.",
    save_success: "Резултатът беше запазен успешно и свързан с кода на ученика.",
    save_queued: "Сървърът е временно недостъпен. Този опит беше запазен локално и ще бъде автоматично синхронизиран, когато връзката се възстанови.",
    open_report_prompt: "Искате ли да отворите отчета сега?",
    loading_data: "Зареждане на данни...",
    monthly_failed: "Не можаха да се заредят гениите на месеца.",
    monthly_title: "Гении на месеца",
    sessions_metric: "Сесии",
    questions_metric: "Въпроси",
    points_metric: "Точки",
    streak_metric: "Най-добра серия",
    student_not_found: "Ученикът не беше намерен или данните не можаха да бъдат заредени.",
    result_title: "Предизвикателството е завършено!",
    result_subtitle: "Вашият резултат от предизвикателството е готов за преглед.",
    result_score: "Общ резултат:",
    result_correct: "Верни отговори:",
    result_saved: "Резултатът беше запазен успешно и свързан с кода на ученика.",
    result_open_report: "Отвори отчет",
    result_continue: "Продължи",
    version_label: "Soroban Core v3.1",
    registration_title: "Добре дошли в MIZAN ANZAN",
    registration_desc: "Създайте своята защитена самоличност в MIZAN и продължете своето персонализирано обучение.",
    registration_language_label: "Език за регистрация",
    registration_language_desc: "Изберете езика, който искате да използвате по време на цялото си изживяване с MIZAN.",
    role_selection_title: "Изберете типа на профила си",
    role_selection_desc: "Изберете типа профил, който най-добре описва как ще използвате MIZAN.",
    role_genius: "Гений",
    role_genius_desc: "За учащи, които искат да тренират, да се усъвършенстват и да следят своя напредък.",
    role_coach: "Треньор",
    role_coach_desc: "За треньори, които управляват обучението, тренировките и напредъка на учениците.",
    role_parent: "Родител",
    role_parent_desc: "За родители или настойници, които искат да следят напредъка на детето си.",
    role_entity: "Организация",
    role_entity_desc: "За училища, академии, центрове, институти, клубове, федерации и тренировъчни организации.",
    genius_full_name_label: "Пълно име на гения",
    genius_full_name_placeholder: "Въведете пълното си име",
    display_name_en_label: "Международно име на английски",
    display_name_en_placeholder: "Въведете името си на английски",
    display_name_en_help: "Това име ще се използва в международните класации, състезания и глобалното признание.",
    display_name_en_required: "Вашето международно име на английски е задължително.",
    display_name_en_invalid: "Моля, въведете валидно международно име, използвайки английски букви.",
    display_name_en_confirm: "Потвърждавам, че това е английското име, което искам да използвам международно.",
    country_placeholder: "Изберете вашата държава",
    country_search_placeholder: "Търсете вашата държава",
    country_help: "Вашата държава ще се използва за международни класации и състезания.",
    entity_name_label: "Име на организацията",
    entity_name_placeholder: "Въведете името на организацията",
    entity_type_label: "Тип организация",
    branch_label: "Клон",
    branch_placeholder: "Изберете клон",
    branch_optional: "Изборът на клон е по желание",
    branch_main: "Основна организация",
    independent_coach: "Независим треньор",
    independent_coach_title: "Независим треньор",
    independent_coach_desc: "Регистрирайте се като независим треньор, без да се присъединявате към организация.",
    independent_coach_note: "Независимите треньори могат да се регистрират без организация или клон.",
    coach_registration_title: "Регистрация на треньор",
    coach_registration_desc: "Създайте своя професионален MIZAN треньорски профил.",
    coach_code_label: "Треньорски код",
    parent_registration_title: "Регистрация на родител",
    parent_registration_desc: "Създайте своя защитен родителски или настойнически профил.",
    parent_code_label: "Родителски код",
    entity_code_label: "Код на организацията",
    entity_code_placeholder: "Въведете кода на вашата организация",
    entity_code_help: "Използвайте този код за достъп до MIZAN профила на вашата организация.",
    create_account_button: "Създаване на профил",
    create_genius_account_button: "Създаване на генийски профил",
    create_coach_account_button: "Създаване на треньорски профил",
    create_parent_account_button: "Създаване на родителски профил",
    create_organization_account_button: "Създаване на организационен профил",
    registration_success_title: "Регистрацията е успешна",
    registration_success_desc: "Вашият MIZAN профил беше създаден успешно.",
    your_genius_code: "Вашият генийски код",
    your_coach_code: "Вашият треньорски код",
    your_parent_code: "Вашият родителски код",
    your_organization_code: "Вашият организационен код",
    save_code_warning: "Моля, запазете своя код на сигурно място. Ще ви е необходим за достъп до вашия MIZAN профил.",
    link_genius_title: "Свържете гений",
    link_genius_desc: "Въведете генийския код, предоставен от учащия.",
    genius_code_label: "Генийски код",
    genius_code_placeholder: "Пример: ANZ-982143",
    link_genius_button: "Свържи гений",
    registration_failed: "Регистрацията не можа да бъде завършена.",
    server_error: "Не успяхме да завършим вашата регистрация. Моля, опитайте отново.",
    required_field: "Това поле е задължително.",
    invalid_name: "Моля, въведете валидно име.",
    invalid_english_name: "Моля, въведете валидно международно име на английски.",
    country_required: "Моля, изберете вашата държава.",
    role_required: "Моля, изберете тип на профила.",
    entity_required: "Моля, въведете информация за вашата организация.",
    branch_required: "Моля, изберете клон.",
    code_invalid: "Кодът е невалиден.",
    code_not_found: "Кодът не беше намерен.",
    code_already_used: "Този код вече се използва.",
    network_error: "Възникна грешка в мрежата. Моля, опитайте отново.",
    back_button: "Назад",
    continue_button: "Продължи",
    cancel_button: "Отказ",
    change_account_type: "Промяна на типа профил",
    switch_account: "Смяна на профила",
    language_label: "Език",
    change_language: "Смяна на езика",
    language_saved: "Езиковите предпочитания бяха запазени.",
    language_loading: "Зареждане на езика...",
    language_unavailable: "Този език е временно недостъпен.",
    monthly_award_label: "Гении на месеца",
    monthly_description: "Гении на месеца",
    reports_label: "Отвори отчет",
    cognitive_profile_label: "Фокус",
    entity_type_school: "За училища",
    entity_type_academy: "академии",
    entity_type_center: "центрове",
    entity_type_institute: "институти",
    entity_type_club: "клубове",
    entity_type_educational_institution: "Образователна институция",
    entity_type_federation: "тренировъчни организации",
    entity_type_training_organization: "Тип организация",
    entity_type_other: "Друго",
    organization_country: "Държава",
    organization_city: "Град",
    branch_code: "Клон — Код на организацията",
    branch_name: "Клон — Име на организацията",
    branch_manager: "Управител на клона",
    international_name_privacy: "Това име ще се използва в международните класации, състезания и глобалното признание.",
    leaderboard_name_notice: "Това име ще се използва в международните класации, състезания и глобалното признание.",
    privacy_notice: "Създайте своята защитена самоличност в MIZAN и продължете своето персонализирано обучение."
};
