/* MIZAN ANZAN — Final Global Locale */
/* Language: bn | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["bn"] = {
    brand_title: "MIZAN ANZAN",
    meta_description: "Mizan Anzan — পেশাদার আনজান এবং সোরোবান প্রশিক্ষণ প্ল্যাটফর্ম",
    language_selector_aria: "ভাষা নির্বাচন",
    answer_placeholder: "ফলাফল এখানে লিখুন",
    platform_subtitle: "মানব উন্নয়নের জন্য আন্তর্জাতিক বিজ্ঞানী কমিশনের প্ল্যাটফর্ম — ফ্রান্স",
    nav_setup: "প্রশিক্ষণ সেটিংস",
    nav_leaderboard: "লিডারবোর্ড (Top 20)",
    nav_trainer: "প্রশিক্ষক পোর্টাল",
    nav_parent: "অভিভাবক পোর্টাল",
    nav_monthly: "মাসের প্রতিভাবান",
    nav_history: "প্রশিক্ষণ ইতিহাস ও রিপোর্ট",
    student_code_label: "প্রতিভাবান কোড:",
    reset_account: "নিবন্ধন / অ্যাকাউন্ট পরিবর্তন",
    preset_kyu_dan_label: "প্রশিক্ষক - প্রশিক্ষণ স্তর নির্ধারণ",
    preset_custom: "-- কাস্টম ম্যানুয়াল সেটআপ --",
    preset_kyu_beginner: "শিক্ষানবিশ স্তর (Kyu 10 - Kyu 7) | 1-2 অঙ্ক - 3-5 সারি",
    preset_kyu_inter: "মধ্যবর্তী স্তর (Kyu 6 - Kyu 4) | 2-3 অঙ্ক - 5-8 সারি",
    preset_kyu_advanced: "উন্নত স্তর (Kyu 3 - Kyu 1) | 3-5 অঙ্ক - 8-12 সারি",
    preset_dan_pro: "পেশাদার স্তর (Dan 1 - Dan 5) | 5-8 অঙ্ক - 15-25 সারি",
    preset_dan_master: "মাস্টার স্তর (Dan 6 - Dan 10) | 8-10 অঙ্ক - 30-50 সারি",
    preset_olympiad_gm: "বিশ্ব অলিম্পিয়াড স্তর (গ্র্যান্ডমাস্টার) | 10-15 অঙ্ক - 50-100 সারি",
    mode_label: "প্রশিক্ষণ মোড",
    mode_flash: "ফ্ল্যাশ আনজান",
    mode_flash_desc: "দ্রুত ক্রমিক ফ্ল্যাশ",
    mode_standard: "স্ট্যান্ডার্ড সোরোবান (স্ট্যাটিক)",
    mode_standard_desc: "সম্পূর্ণ স্ট্যাটিক সংখ্যা প্রদর্শন",
    level_label: "স্তর (কঠোর সোরোবান নিয়ম)",
    level_l1: "L1 - সরাসরি যোগ/বিয়োগ (কোন পূরক নেই)",
    level_l2: "L2 - 5 এর বন্ধু (5 পূরক)",
    level_l3: "L3 - 10 এর বন্ধু (10 পূরক)",
    level_lm: "LM - ব্যাপক মিশ্র (সমস্ত নিয়ম)",
    age_label: "বয়স গ্রুপ",
    age_under_6: "6 বছরের কম",
    age_7_9: "7 - 9 বছর",
    age_10_12: "10 - 12 বছর",
    age_13_15: "13 - 15 বছর",
    age_16_plus: "16+ বছর",
    digits_label: "অঙ্ক",
    rows_label: "সারি",
    op_label: "অপারেশন প্রকার",
    op_add: "শুধু যোগ",
    op_sub: "শুধু বিয়োগ",
    op_mix: "মিশ্র (যোগ এবং বিয়োগ)",
    duration_label: "চ্যালেঞ্জ সময় (সেকেন্ড)",
    rest_label: "বিশ্রাম সময়",
    rest_1s: "1 সেকেন্ড",
    rest_2s: "2 সেকেন্ড",
    rest_3s: "3 সেকেন্ড",
    rest_4s: "4 সেকেন্ড",
    rest_5s: "5 সেকেন্ড",
    speed_label: "প্রদর্শন গতি (সেকেন্ড)",
    tts_label: "সংখ্যা উচ্চারণ",
    start_button: "চ্যালেঞ্জ শুরু করুন",
    timer_label: "অবশিষ্ট সময়:",
    score_label: "স্কোর:",
    exit_button: "প্রস্থান",
    submit_answer: "উত্তর জমা দিন",
    welcome_title: "Mizan Anzan এ স্বাগতম",
    welcome_desc: "আপনার ট্র্যাকিং কোড তৈরি করতে আপনার বিবরণ নিবন্ধন করুন",
    fullname_label: "প্রতিভাবানের সম্পূর্ণ নাম",
    fullname_ph: "আপনার সম্পূর্ণ নাম লিখুন",
    country_label: "দেশ",
    country_ph: "উদাহরণ: ফ্রান্স, মিশর, সৌদি আরব",
    generate_code_btn: "প্রতিভাবান কোড তৈরি করুন এবং প্রবেশ করুন",
    countdown_start: "শুরু!",
    generation_error: "এই সেটিংসের সাথে বৈধ চ্যালেঞ্জ তৈরি করা সম্ভব নয়।",
    correct_feedback: "সঠিক উত্তর! দারুণ কাজ, প্রতিভাবান।",
    incorrect_feedback: "ভুল। সঠিক উত্তর ছিল:",
    invalid_integer: "অনুগ্রহ করে একটি বৈধ পূর্ণসংখ্যা লিখুন।",
    challenge_complete: "চ্যালেঞ্জ সম্পূর্ণ!",
    total_score: "মোট স্কোর:",
    correct_answers: "সঠিক উত্তর:",
    of_word: "এর মধ্যে",
    trainer_title: "প্রশিক্ষক নিয়ন্ত্রণ প্যানেল",
    parent_title: "অভিভাবক অগ্রগতি প্যানেল",
    portal_desc: "অগ্রগতি এবং বিস্তারিত বিশ্লেষণ দেখতে প্রতিভাবান কোড লিখুন",
    lookup_placeholder: "প্রতিভাবান কোড লিখুন (যেমন: ANZ-982143)",
    follow_up: "দেখুন",
    enter_code: "অনুগ্রহ করে প্রতিভাবান কোড লিখুন",
    tracked_student: "ট্র্যাক করা প্রতিভাবান:",
    active_account: "সক্রিয় নিবন্ধিত অ্যাকাউন্ট",
    genius_fallback: "আনজান প্রতিভাবান",
    focus_metric: "ফোকাস",
    accuracy_metric: "সঠিকতা",
    perf_metric: "কর্মক্ষমতা ও গতি",
    growth_metric: "বৃদ্ধি",
    th_rank: "#",
    th_code: "কোড",
    th_country: "দেশ",
    th_name: "প্রতিভাবানের নাম",
    th_mode: "মোড",
    th_age: "বয়স গ্রুপ",
    th_level: "স্তর",
    th_digits: "অঙ্ক",
    th_rows: "সারি",
    th_operation: "অপারেশন",
    th_duration: "সময়কাল",
    th_speed: "গতি",
    th_points: "পয়েন্ট",
    leaderboard_title: "লিডারবোর্ড — Top 20",
    leaderboard_empty: "এখনও কোন ফলাফল নেই।",
    mode_flash_short: "ফ্ল্যাশ আনজান",
    mode_standard_short: "স্ট্যান্ডার্ড সোরোবান",
    op_add_short: "যোগ",
    op_sub_short: "বিয়োগ",
    op_mix_short: "মিশ্র",
    subtract_speech: "বিয়োগ",
    seconds_short: "সে",
    challenge_invalid: "চ্যালেঞ্জ শুরু করা যায়নি। সেটিংস চেক করুন এবং আবার চেষ্টা করুন।",
    challenge_generation_failed: "চ্যালেঞ্জ তৈরি করা যায়নি। পরীক্ষা শুরু হয়নি। অনুগ্রহ করে প্রশিক্ষণ সেটিংস চেক করুন।",
    save_failed: "চ্যালেঞ্জ ফলাফল সার্ভারে সংরক্ষণ করা যায়নি। এই প্রচেষ্টা রিপোর্ট বা লিডারবোর্ডে গণনা করা হয়নি।",
    save_success: "ফলাফল সফলভাবে সংরক্ষণ করা হয়েছে এবং ছাত্র কোডের সাথে লিঙ্ক করা হয়েছে।",
    save_queued: "সার্ভার অস্থায়ীভাবে অনুপলব্ধ। এই প্রচেষ্টা স্থানীয়ভাবে সংরক্ষণ করা হয়েছে এবং সংযোগ ফিরে এলে স্বয়ংক্রিয়ভাবে সিঙ্ক্রোনাইজ হবে।",
    open_report_prompt: "আপনি কি এখন রিপোর্ট খুলতে চান?",
    loading_data: "ডেটা লোড হচ্ছে...",
    monthly_failed: "মাসের প্রতিভাবানদের লোড করা যায়নি।",
    monthly_title: "মাসের প্রতিভাবান",
    sessions_metric: "সেশন",
    questions_metric: "প্রশ্ন",
    points_metric: "পয়েন্ট",
    streak_metric: "সেরা ধারা",
    student_not_found: "ছাত্র পাওয়া যায়নি বা ডেটা লোড করা যায়নি।",
    result_title: "চ্যালেঞ্জ সম্পূর্ণ!",
    result_subtitle: "আপনার চ্যালেঞ্জ ফলাফল পর্যালোচনার জন্য প্রস্তুত।",
    result_score: "মোট স্কোর:",
    result_correct: "সঠিক উত্তর:",
    result_saved: "ফলাফল সফলভাবে সংরক্ষণ করা হয়েছে এবং ছাত্র কোডের সাথে লিঙ্ক করা হয়েছে।",
    result_open_report: "রিপোর্ট খুলুন",
    result_continue: "চালিয়ে যান",
    version_label: "Soroban Core v3.1",
    registration_title: "MIZAN ANZAN-এ স্বাগতম",
    registration_desc: "আপনার নিরাপদ MIZAN পরিচয় তৈরি করুন এবং আপনার ব্যক্তিগতকৃত শিক্ষার যাত্রা চালিয়ে যান।",
    registration_language_label: "নিবন্ধনের ভাষা",
    registration_language_desc: "আপনার MIZAN অভিজ্ঞতা জুড়ে আপনি যে ভাষা ব্যবহার করতে চান তা নির্বাচন করুন।",
    role_selection_title: "আপনার অ্যাকাউন্টের ধরন নির্বাচন করুন",
    role_selection_desc: "আপনি কীভাবে MIZAN ব্যবহার করবেন তা সবচেয়ে ভালোভাবে বর্ণনা করে এমন অ্যাকাউন্টের ধরন নির্বাচন করুন।",
    role_genius: "প্রতিভাবান",
    role_genius_desc: "যে শিক্ষার্থীরা প্রশিক্ষণ নিতে, উন্নতি করতে এবং তাদের নিজস্ব অগ্রগতি ট্র্যাক করতে চান তাদের জন্য।",
    role_coach: "কোচ",
    role_coach_desc: "যে প্রশিক্ষকরা শিক্ষা, প্রশিক্ষণ এবং শিক্ষার্থীদের অগ্রগতি পরিচালনা করেন তাদের জন্য।",
    role_parent: "অভিভাবক",
    role_parent_desc: "যে অভিভাবক বা সংরক্ষকরা তাদের সন্তানের অগ্রগতি অনুসরণ করতে চান তাদের জন্য।",
    role_entity: "সংস্থা",
    role_entity_desc: "স্কুল, একাডেমি, কেন্দ্র, ইনস্টিটিউট, ক্লাব, ফেডারেশন এবং প্রশিক্ষণ সংস্থাগুলির জন্য।",
    genius_full_name_label: "প্রতিভাবানের পূর্ণ নাম",
    genius_full_name_placeholder: "আপনার পূর্ণ নাম লিখুন",
    display_name_en_label: "ইংরেজিতে আন্তর্জাতিক নাম",
    display_name_en_placeholder: "ইংরেজিতে আপনার নাম লিখুন",
    display_name_en_help: "এই নামটি আন্তর্জাতিক লিডারবোর্ড, প্রতিযোগিতা এবং বৈশ্বিক স্বীকৃতিতে ব্যবহার করা হবে।",
    display_name_en_required: "আপনার আন্তর্জাতিক ইংরেজি নাম প্রয়োজন।",
    display_name_en_invalid: "অনুগ্রহ করে ইংরেজি অক্ষর ব্যবহার করে একটি বৈধ আন্তর্জাতিক নাম লিখুন।",
    display_name_en_confirm: "আমি নিশ্চিত করছি যে এটি ইংরেজি নাম যা আমি আন্তর্জাতিকভাবে ব্যবহার করতে চাই।",
    country_placeholder: "আপনার দেশ নির্বাচন করুন",
    country_search_placeholder: "আপনার দেশ অনুসন্ধান করুন",
    country_help: "আপনার দেশ আন্তর্জাতিক র্যাঙ্কিং এবং প্রতিযোগিতার জন্য ব্যবহার করা হবে।",
    entity_name_label: "সংস্থার নাম",
    entity_name_placeholder: "সংস্থার নাম লিখুন",
    entity_type_label: "সংস্থার ধরন",
    branch_label: "শাখা",
    branch_placeholder: "একটি শাখা নির্বাচন করুন",
    branch_optional: "শাখা নির্বাচন ঐচ্ছিক",
    branch_main: "প্রধান সংস্থা",
    independent_coach: "স্বাধীন কোচ",
    independent_coach_title: "স্বাধীন কোচ",
    independent_coach_desc: "কোনও সংস্থায় যোগ না দিয়ে স্বাধীন কোচ হিসাবে নিবন্ধন করুন।",
    independent_coach_note: "স্বাধীন কোচরা সংস্থা বা শাখা ছাড়াই নিবন্ধন করতে পারেন।",
    coach_registration_title: "কোচ নিবন্ধন",
    coach_registration_desc: "আপনার পেশাদার MIZAN কোচ অ্যাকাউন্ট তৈরি করুন।",
    coach_code_label: "কোচ কোড",
    parent_registration_title: "অভিভাবক নিবন্ধন",
    parent_registration_desc: "আপনার নিরাপদ অভিভাবক বা সংরক্ষক অ্যাকাউন্ট তৈরি করুন।",
    parent_code_label: "অভিভাবক কোড",
    entity_code_label: "সংস্থা কোড",
    entity_code_placeholder: "আপনার সংস্থা কোড লিখুন",
    entity_code_help: "আপনার সংস্থার MIZAN অ্যাকাউন্ট অ্যাক্সেস করতে এই কোডটি ব্যবহার করুন।",
    create_account_button: "অ্যাকাউন্ট তৈরি করুন",
    create_genius_account_button: "প্রতিভাবান অ্যাকাউন্ট তৈরি করুন",
    create_coach_account_button: "কোচ অ্যাকাউন্ট তৈরি করুন",
    create_parent_account_button: "অভিভাবক অ্যাকাউন্ট তৈরি করুন",
    create_organization_account_button: "সংস্থা অ্যাকাউন্ট তৈরি করুন",
    registration_success_title: "নিবন্ধন সফল হয়েছে",
    registration_success_desc: "আপনার MIZAN অ্যাকাউন্ট সফলভাবে তৈরি করা হয়েছে।",
    your_genius_code: "আপনার প্রতিভাবান কোড",
    your_coach_code: "আপনার কোচ কোড",
    your_parent_code: "আপনার অভিভাবক কোড",
    your_organization_code: "আপনার সংস্থা কোড",
    save_code_warning: "অনুগ্রহ করে আপনার কোডটি নিরাপদে সংরক্ষণ করুন। আপনার MIZAN অ্যাকাউন্ট অ্যাক্সেস করতে আপনার এটি প্রয়োজন হবে।",
    link_genius_title: "একটি প্রতিভাবান লিঙ্ক করুন",
    link_genius_desc: "শিক্ষার্থী দ্বারা প্রদত্ত প্রতিভাবান কোডটি লিখুন।",
    genius_code_label: "প্রতিভাবান কোড",
    genius_code_placeholder: "উদাহরণ: ANZ-982143",
    link_genius_button: "প্রতিভাবান লিঙ্ক করুন",
    registration_failed: "নিবন্ধন সম্পূর্ণ করা যায়নি।",
    server_error: "আমরা আপনার নিবন্ধন সম্পূর্ণ করতে পারিনি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    required_field: "এই ক্ষেত্রটি প্রয়োজনীয়।",
    invalid_name: "অনুগ্রহ করে একটি বৈধ নাম লিখুন।",
    invalid_english_name: "অনুগ্রহ করে ইংরেজিতে একটি বৈধ আন্তর্জাতিক নাম লিখুন।",
    country_required: "অনুগ্রহ করে আপনার দেশ নির্বাচন করুন।",
    role_required: "অনুগ্রহ করে একটি অ্যাকাউন্টের ধরন নির্বাচন করুন।",
    entity_required: "অনুগ্রহ করে আপনার সংস্থার তথ্য লিখুন।",
    branch_required: "অনুগ্রহ করে একটি শাখা নির্বাচন করুন।",
    code_invalid: "কোডটি অবৈধ।",
    code_not_found: "কোডটি খুঁজে পাওয়া যায়নি।",
    code_already_used: "এই কোডটি ইতিমধ্যে ব্যবহৃত হচ্ছে।",
    network_error: "একটি সংযোগ ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    back_button: "পিছনে",
    continue_button: "চালিয়ে যান",
    cancel_button: "বাতিল করুন",
    change_account_type: "অ্যাকাউন্টের ধরন পরিবর্তন করুন",
    switch_account: "অ্যাকাউন্ট পরিবর্তন করুন",
    language_label: "ভাষা",
    change_language: "ভাষা পরিবর্তন করুন",
    language_saved: "ভাষার পছন্দ সংরক্ষণ করা হয়েছে।",
    language_loading: "ভাষা লোড হচ্ছে...",
    language_unavailable: "এই ভাষাটি সাময়িকভাবে অনুপলব্ধ।",
    monthly_award_label: "মাসের প্রতিভাবান",
    monthly_description: "মাসের প্রতিভাবান",
    reports_label: "রিপোর্ট খুলুন",
    cognitive_profile_label: "ফোকাস",
    entity_type_school: "স্কুল",
    entity_type_academy: "একাডেমি",
    entity_type_center: "কেন্দ্র",
    entity_type_institute: "ইনস্টিটিউট",
    entity_type_club: "ক্লাব",
    entity_type_educational_institution: "শিক্ষা প্রতিষ্ঠান",
    entity_type_federation: "সংস্থার ধরন",
    entity_type_training_organization: "সংস্থার ধরন",
    entity_type_other: "অন্যান্য",
    organization_country: "দেশ",
    organization_city: "শহর",
    branch_code: "শাখা — সংস্থা কোড",
    branch_name: "শাখা — সংস্থার নাম",
    branch_manager: "শাখা ব্যবস্থাপক",
    international_name_privacy: "এই নামটি আন্তর্জাতিক লিডারবোর্ড, প্রতিযোগিতা এবং বৈশ্বিক স্বীকৃতিতে ব্যবহার করা হবে।",
    leaderboard_name_notice: "এই নামটি আন্তর্জাতিক লিডারবোর্ড, প্রতিযোগিতা এবং বৈশ্বিক স্বীকৃতিতে ব্যবহার করা হবে।",
    privacy_notice: "আপনার নিরাপদ MIZAN পরিচয় তৈরি করুন এবং আপনার ব্যক্তিগতকৃত শিক্ষার যাত্রা চালিয়ে যান।"
};
