/* MIZAN ANZAN — Final Global Locale */
/* Language: ckb | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["ckb"] = {
    brand_title: "میزان ئانزان",
    meta_description: "میزان ئانزان — پلاتفۆرمی پیشەیی ڕاهێنانی ئانزان و سۆرۆبان",
    language_selector_aria: "هەڵبژاردنی زمان",
    answer_placeholder: "ئەنجامەکە لێرە بنووسە",
    platform_subtitle: "پلاتفۆرمی کۆمسیۆنی نێودەوڵەتیی زانایان بۆ گەشەپێدانی مرۆیی — فەرەنسا",
    nav_setup: "ڕێکخستنەکانی ڕاهێنان",
    nav_leaderboard: "خشتەی پێشەنگان (٢٠ی یەکەم)",
    nav_trainer: "پۆرتاڵی ڕاهێنەر",
    nav_parent: "پۆرتاڵی دایک و باوک",
    nav_monthly: "زیرەکانی مانگ",
    nav_history: "مێژووی ڕاهێنان و ڕاپۆرتەکان",
    student_code_label: "کۆدی زیرەک:",
    reset_account: "تۆمارکردن / گۆڕینی هەژمار",
    preset_kyu_dan_label: "ڕاهێنەر — دیاریکردنی ئاستی ڕاهێنان",
    preset_custom: "-- ڕێکخستنی دەستی تایبەت --",
    preset_kyu_beginner: "ئاستی دەستپێکەر (Kyu 10 - Kyu 7) | ١-٢ ژمارە — ٣-٥ ڕیز",
    preset_kyu_inter: "ئاستی ناوەندی (Kyu 6 - Kyu 4) | ٢-٣ ژمارە — ٥-٨ ڕیز",
    preset_kyu_advanced: "ئاستی پێشکەوتوو (Kyu 3 - Kyu 1) | ٣-٥ ژمارە — ٨-١٢ ڕیز",
    preset_dan_pro: "ئاستی پیشەیی (Dan 1 - Dan 5) | ٥-٨ ژمارە — ١٥-٢٥ ڕیز",
    preset_dan_master: "ئاستی ماستەر (Dan 6 - Dan 10) | ٨-١٠ ژمارە — ٣٠-٥٠ ڕیز",
    preset_olympiad_gm: "ئاستی ئۆڵمپیادی جیهانی (Grandmaster) | ١٠-١٥ ژمارە — ٥٠-١٠٠ ڕیز",
    mode_label: "شێوازی ڕاهێنان",
    mode_flash: "ئانزانی فلاش",
    mode_flash_desc: "پیشاندانی ژمارەکان بە شێوەی زنجیرەیی و خێرا",
    mode_standard: "سۆرۆبانی ستاندارد (جێگیر)",
    mode_standard_desc: "پیشاندانی تەواوی ژمارەکان بە شێوەی جێگیر",
    level_label: "ئاست (بەپێی یاساکانی سەختی سۆرۆبان)",
    level_l1: "L1 — کۆکردنەوە و لێکدانەوەی ڕاستەوخۆ (بێ تەواوکەر)",
    level_l2: "L2 — هاوڕێکانی ٥ (تەواوکەرەکانی ٥)",
    level_l3: "L3 — هاوڕێکانی ١٠ (تەواوکەرەکانی ١٠)",
    level_lm: "LM — تێکەڵی گشتگیر (هەموو یاساکان)",
    age_label: "گرووپی تەمەن",
    age_under_6: "کەمتر لە ٦ ساڵ",
    age_7_9: "٧ - ٩ ساڵ",
    age_10_12: "١٠ - ١٢ ساڵ",
    age_13_15: "١٣ - ١٥ ساڵ",
    age_16_plus: "١٦ ساڵ و زیاتر",
    digits_label: "ژمارەکان",
    rows_label: "ڕیزەکان",
    op_label: "جۆری کردار",
    op_add: "تەنها کۆکردنەوە",
    op_sub: "تەنها لێکدانەوە",
    op_mix: "تێکەڵ (کۆکردنەوە و لێکدانەوە)",
    duration_label: "ماوەی چالاکی (چرکە)",
    rest_label: "کاتی پشوودان",
    rest_1s: "١ چرکە",
    rest_2s: "٢ چرکە",
    rest_3s: "٣ چرکە",
    rest_4s: "٤ چرکە",
    rest_5s: "٥ چرکە",
    speed_label: "خێرایی پیشاندانی ژمارەکان (بە چرکە)",
    tts_label: "خوێندنەوەی ژمارەکان",
    start_button: "دەستپێکردنی چالاکی",
    timer_label: "کاتی ماوە:",
    score_label: "خاڵ:",
    exit_button: "دەرچوون",
    submit_answer: "ناردنی وەڵام",
    welcome_title: "بەخێربێیت بۆ میزانی ئانزان",
    welcome_desc: "تکایە زانیارییەکانت تۆمار بکە بۆ بەدەستهێنانی کۆدی شوێنکەوتنت",
    fullname_label: "ناوی تەواوی زیرەک",
    fullname_ph: "ناوی تەواوت بنووسە",
    country_label: "وڵات",
    country_ph: "بۆ نموونە: فەرەنسا، میسر، عێراق",
    generate_code_btn: "دروستکردنی کۆدی زیرەک و چوونەژوورەوە",
    countdown_start: "دەستپێبکە!",
    generation_error: "نەتوانرا چالاکییەکی دروست بەو ڕێکخستنە دروست بکرێت.",
    correct_feedback: "وەڵامەکە ڕاستە! دەستخۆش زیرەک.",
    incorrect_feedback: "هەڵەیە. وەڵامی ڕاست ئەمە بوو:",
    invalid_integer: "تکایە ژمارەیەکی تەواوی دروست بنووسە.",
    challenge_complete: "چالاکییەکە تەواو بوو!",
    total_score: "کۆی خاڵەکان:",
    correct_answers: "ژمارەی وەڵامە ڕاستەکان:",
    of_word: "لە",
    trainer_title: "پانێڵی کۆنترۆڵی ڕاهێنەر",
    parent_title: "پانێڵی بەدواداچوونی دایک و باوک",
    portal_desc: "کۆدی زیرەک بنووسە بۆ بینینی پێشکەوتن و شیکردنەوەی ورد",
    lookup_placeholder: "کۆدی زیرەک بنووسە (بۆ نموونە: ANZ-982143)",
    follow_up: "بەدواداچوون",
    enter_code: "تکایە کۆدی زیرەک بنووسە",
    tracked_student: "زیرەکی بەدواداچوونکراو:",
    active_account: "هەژماری چالاک و تۆمارکراو",
    genius_fallback: "زیرەکی ئانزان",
    focus_metric: "سەرنج",
    accuracy_metric: "وردی",
    perf_metric: "ئەدا و خێرایی",
    growth_metric: "پێشکەوتن",
    th_rank: "#",
    th_code: "کۆد",
    th_country: "وڵات",
    th_name: "ناوی زیرەک",
    th_mode: "شێوازی ڕاهێنان",
    th_age: "گرووپی تەمەن",
    th_level: "ئاست",
    th_digits: "ژمارەکان",
    th_rows: "ڕیزەکان",
    th_operation: "کردار",
    th_duration: "ماوە",
    th_speed: "خێرایی",
    th_points: "خاڵەکان",
    leaderboard_title: "خشتەی پێشەنگان — ٢٠ی یەکەم",
    leaderboard_empty: "هێشتا هیچ ئەنجامێک نییە.",
    mode_flash_short: "فلاشی ئانزان",
    mode_standard_short: "سۆرۆبانی ستاندارد",
    op_add_short: "کۆکردنەوە",
    op_sub_short: "لێکدانەوە",
    op_mix_short: "تێکەڵ",
    subtract_speech: "لێکدانەوە",
    seconds_short: "چرکە",
    challenge_invalid: "نەتوانرا چالاکییەکە دەستپێبکرێت. ڕێکخستنەکان بپشکنە و دووبارە هەوڵ بدە.",
    save_failed: "نەتوانرا ئەنجامی چالاکی لەسەر ڕاژەکار پاشەکەوت بکرێت. ئەم هەوڵە لە ڕاپۆرتەکان یان خشتەی پێشەنگاندا هەژمار ناکرێت.",
    save_success: "ئەنجامەکە بە سەرکەوتوویی پاشەکەوت کرا و بە کۆدی خوێندکارەوە بەسترا.",
    save_queued: "بۆ ماوەیەک پەیوەندی بە ڕاژەکارەوە بەردەست نییە. هەوڵەکە لەسەر ئامێرەکەت پاشەکەوت کرا و دوای گەڕانەوەی پەیوەندی بە شێوەی خۆکار هاوکات دەکرێت.",
    open_report_prompt: "دەتەوێت ئێستا ڕاپۆرتەکە بکەیتەوە؟",
    challenge_generation_failed: "نەتوانرا چالاکییەکە دروست بکرێت. تاقیکردنەوەکە دەستی پێ نەکرد. تکایە ڕێکخستنەکانی ڕاهێنان بپشکنە.",
    loading_data: "بارکردنی زانیارییەکان...",
    monthly_failed: "نەتوانرا زیرەکانی مانگ باربکرێن.",
    monthly_title: "زیرەکانی مانگ",
    sessions_metric: "دانیشتنەکان",
    questions_metric: "پرسیارەکان",
    points_metric: "خاڵەکان",
    streak_metric: "باشترین زنجیرە",
    student_not_found: "خوێندکار نەدۆزرایەوە یان نەتوانرا زانیارییەکانی باربکرێن.",
    result_title: "چالاکییەکە تەواو بوو!",
    result_subtitle: "ئەنجامی چالاکییەکەت ئامادەیە بۆ پێداچوونەوە.",
    result_score: "کۆی خاڵەکان:",
    result_correct: "وەڵامە ڕاستەکان:",
    result_saved: "ئەنجامەکە بە سەرکەوتوویی پاشەکەوت کرا و بە کۆدی خوێندکارەوە بەسترا.",
    result_open_report: "کردنەوەی ڕاپۆرت",
    result_continue: "بەردەوامبوون",
    version_label: "Soroban Core v3.1",
    registration_title: "بەخێربێیت بۆ MIZAN ANZAN",
    registration_desc: "ناسنامەی پارێزراوی خۆت لە MIZAN دروست بکە و گەشتی فێربوونی تایبەتی خۆت بەردەوام بە.",
    registration_language_label: "زمانی تۆمارکردن",
    registration_language_desc: "ئەو زمانە هەڵبژێرە کە دەتەوێت لە درێژایی ئەزموونی MIZAN-ت بەکاری بهێنیت.",
    role_selection_title: "جۆری هەژمارەکەت هەڵبژێرە",
    role_selection_desc: "ئەو جۆرە هەژمارە هەڵبژێرە کە باشتر وەسفی ئەوە دەکات کە چۆن MIZAN بەکار دەهێنیت.",
    role_genius: "نابەرە",
    role_genius_desc: "بۆ ئەو فێرخوازانەی کە دەیانەوێت ڕاهێنان بکەن، باشتر بن و پێشکەوتنی خۆیان بشۆپێنن.",
    role_coach: "ڕاهێنەر",
    role_coach_desc: "بۆ ئەو ڕاهێنەرانەی کە فێربوون، ڕاهێنان و پێشکەوتنی خوێندکاران بەڕێوە دەبەن.",
    role_parent: "دایک یان باوک",
    role_parent_desc: "بۆ دایک و باوکان یان چاودێرانەی کە دەیانەوێت پێشکەوتنی منداڵەکەیان بشۆپێنن.",
    role_entity: "ڕێکخراو",
    role_entity_desc: "بۆ قوتابخانە، ئەکادیمیا، ناوەند، پەیمانگا، یانە، فیدراسیۆن و ڕێکخراوەکانی ڕاهێنان.",
    genius_full_name_label: "ناوی تەواوی نابەرە",
    genius_full_name_placeholder: "ناوی تەواوی خۆت بنووسە",
    display_name_en_label: "ناوی نێودەوڵەتی بە ئینگلیزی",
    display_name_en_placeholder: "ناوی خۆت بە ئینگلیزی بنووسە",
    display_name_en_help: "ئەم ناوە لە تابلۆی پێشەنگی نێودەوڵەتی، پێشبڕکێکان و ناساندنی جیهانیدا بەکار دەهێنرێت.",
    display_name_en_required: "ناوی نێودەوڵەتی ئینگلیزی پێویستە.",
    display_name_en_invalid: "تکایە ناوێکی نێودەوڵەتی دروست بە پیتی ئینگلیزی بنووسە.",
    display_name_en_confirm: "من پشتڕاست دەکەمەوە کە ئەمە ئەو ناوە ئینگلیزیەیە کە دەمەوێت بە شێوەی نێودەوڵەتی بەکاری بهێنم.",
    country_placeholder: "وڵاتەکەت هەڵبژێرە",
    country_search_placeholder: "بۆ وڵاتەکەت بگەرێ",
    country_help: "وڵاتەکەت بۆ پلەبەندی و پێشبڕکێکانی نێودەوڵەتی بەکار دەهێنرێت.",
    entity_name_label: "ناوی ڕێکخراو",
    entity_name_placeholder: "ناوی ڕێکخراوەکە بنووسە",
    entity_type_label: "جۆری ڕێکخراو",
    branch_label: "لق",
    branch_placeholder: "لقێک هەڵبژێرە",
    branch_optional: "هەڵبژاردنی لق ئارەزوومەندانەیە",
    branch_main: "ڕێکخراوی سەرەکی",
    independent_coach: "ڕاهێنەری سەربەخۆ",
    independent_coach_title: "ڕاهێنەری سەربەخۆ",
    independent_coach_desc: "وەک ڕاهێنەری سەربەخۆ بەبێ پەیوەندیکردن بە ڕێکخراوێکەوە تۆمار بکە.",
    independent_coach_note: "ڕاهێنەرە سەربەخۆکان دەتوانن بەبێ ڕێکخراو یان لق تۆمار بکەن.",
    coach_registration_title: "تۆمارکردنی ڕاهێنەر",
    coach_registration_desc: "هەژماری پیشەگەری ڕاهێنەری MIZAN دروست بکە.",
    coach_code_label: "کۆدی ڕاهێنەر",
    parent_registration_title: "تۆمارکردنی دایک یان باوک",
    parent_registration_desc: "هەژماری پارێزراوی دایک یان باوک یان چاودێر دروست بکە.",
    parent_code_label: "کۆدی دایک یان باوک",
    entity_code_label: "کۆدی ڕێکخراو",
    entity_code_placeholder: "کۆدی ڕێکخراوەکەت بنووسە",
    entity_code_help: "ئەم کۆدە بەکاربهێنە بۆ دەستپێگەیشتن بە هەژماری MIZAN ی ڕێکخراوەکەت.",
    create_account_button: "هەژمار دروست بکە",
    create_genius_account_button: "هەژماری نابەرە دروست بکە",
    create_coach_account_button: "هەژماری ڕاهێنەر دروست بکە",
    create_parent_account_button: "هەژماری دایک یان باوک دروست بکە",
    create_organization_account_button: "هەژماری ڕێکخراو دروست بکە",
    registration_success_title: "تۆمارکردن سەرکەوتوو بوو",
    registration_success_desc: "هەژماری MIZAN ی تۆ بە سەرکەوتوویی دروست کرا.",
    your_genius_code: "کۆدی نابەرەی تۆ",
    your_coach_code: "کۆدی ڕاهێنەری تۆ",
    your_parent_code: "کۆدی دایک یان باوکی تۆ",
    your_organization_code: "کۆدی ڕێکخراوی تۆ",
    save_code_warning: "تکایە کۆدەکەت بە شێوەیەکی پارێزراو هەڵگرە. پێویستت پێی دەبێت بۆ دەستپێگەیشتن بە هەژماری MIZAN ی تۆ.",
    link_genius_title: "نابەرەیەک ببەستە",
    link_genius_desc: "کۆدی نابەرەی کە لەلایەن فێرخوازەوە پێشکەش کراوە بنووسە.",
    genius_code_label: "کۆدی نابەرە",
    genius_code_placeholder: "نموونە: ANZ-982143",
    link_genius_button: "نابەرە ببەستە",
    registration_failed: "تۆمارکردن نەکرا تەواو بکرێت.",
    server_error: "نەتوانرا تۆمارکردنەکەت تەواو بکرێت. تکایە هەوڵبدەرەوە.",
    required_field: "ئەم بوارە پێویستە.",
    invalid_name: "تکایە ناوێکی دروست بنووسە.",
    invalid_english_name: "تکایە ناوێکی نێودەوڵەتی دروست بە ئینگلیزی بنووسە.",
    country_required: "تکایە وڵاتەکەت هەڵبژێرە.",
    role_required: "تکایە جۆرێکی هەژمار هەڵبژێرە.",
    entity_required: "تکایە زانیارییەکانی ڕێکخراوەکەت بنووسە.",
    branch_required: "تکایە لقێک هەڵبژێرە.",
    code_invalid: "کۆدەکە نادروستە.",
    code_not_found: "کۆدەکە نەدۆزرایەوە.",
    code_already_used: "ئەم کۆدە پێشتر بەکارهێنراوە.",
    network_error: "هەڵەیەکی پەیوەندی ڕوویدا. تکایە هەوڵبدەرەوە.",
    back_button: "گەڕانەوە",
    continue_button: "بەردەوام بە",
    cancel_button: "پاشگەزبوونەوە",
    change_account_type: "جۆری هەژمار بگۆڕە",
    switch_account: "هەژمار بگۆڕە",
    language_label: "زمان",
    change_language: "زمان بگۆڕە",
    language_saved: "هەڵبژاردنی زمان پاشەکەوت کرا.",
    language_loading: "زمان بار دەبێت...",
    language_unavailable: "ئەم زمانە بە شێوەی کاتی بەردەست نییە.",
    monthly_award_label: "زیرەکانی مانگ",
    monthly_description: "زیرەکانی مانگ",
    reports_label: "کردنەوەی ڕاپۆرت",
    cognitive_profile_label: "سەرنج",
    entity_type_school: "قوتابخانە",
    entity_type_academy: "ئەکادیمیا",
    entity_type_center: "ناوەندی ڕاهێنان",
    entity_type_institute: "پەیمانگا",
    entity_type_club: "یانە",
    entity_type_educational_institution: "دامەزراوەی پەروەردەیی",
    entity_type_federation: "فیدراسیۆن",
    entity_type_training_organization: "ڕێکخراوی ڕاهێنان",
    entity_type_other: "هی تر",
    organization_country: "وڵات",
    organization_city: "شار",
    branch_code: "لق — کۆدی ڕێکخراو",
    branch_name: "لق — ناوی ڕێکخراو",
    branch_manager: "بەڕێوەبەری لق",
    international_name_privacy: "ئەم ناوە لە تابلۆی پێشەنگی نێودەوڵەتی، پێشبڕکێکان و ناساندنی جیهانیدا بەکار دەهێنرێت.",
    leaderboard_name_notice: "ئەم ناوە لە تابلۆی پێشەنگی نێودەوڵەتی، پێشبڕکێکان و ناساندنی جیهانیدا بەکار دەهێنرێت.",
    privacy_notice: "ناسنامەی پارێزراوی خۆت لە MIZAN دروست بکە و گەشتی فێربوونی تایبەتی خۆت بەردەوام بە."
};
