/* MIZAN ANZAN — Final Global Locale */
/* Language: cs | Keys: 215 */
window.I18nLocales = window.I18nLocales || {};
window.I18nLocales["cs"] = {
    brand_title: "MIZAN ANZAN",
    meta_description: "Mizan Anzan — profesionální tréninková platforma Anzan a Soroban",
    language_selector_aria: "Výběr jazyka",
    answer_placeholder: "Zadejte výsledek zde",
    platform_subtitle: "Platforma Mezinárodní komise vědců pro rozvoj lidských zdrojů — Francie",
    nav_setup: "Nastavení tréninku",
    nav_leaderboard: "Žebříček (Top 20)",
    nav_trainer: "Portál trenéra",
    nav_parent: "Portál rodiče",
    nav_monthly: "Géniové měsíce",
    nav_history: "Historie tréninku a zprávy",
    student_code_label: "Kód génia:",
    reset_account: "Registrovat / Změnit účet",
    preset_kyu_dan_label: "Trenér - Nastavení úrovně tréninku",
    preset_custom: "-- Vlastní ruční nastavení --",
    preset_kyu_beginner: "Začátečnická úroveň (Kyu 10 - Kyu 7) | 1-2 číslice - 3-5 řádků",
    preset_kyu_inter: "Střední úroveň (Kyu 6 - Kyu 4) | 2-3 číslice - 5-8 řádků",
    preset_kyu_advanced: "Pokročilá úroveň (Kyu 3 - Kyu 1) | 3-5 číslic - 8-12 řádků",
    preset_dan_pro: "Profesionální úroveň (Dan 1 - Dan 5) | 5-8 číslic - 15-25 řádků",
    preset_dan_master: "Mistrovská úroveň (Dan 6 - Dan 10) | 8-10 číslic - 30-50 řádků",
    preset_olympiad_gm: "Úroveň světové olympiády (Velmistr) | 10-15 číslic - 50-100 řádků",
    mode_label: "Režim tréninku",
    mode_flash: "Flash Anzan",
    mode_flash_desc: "Rychlá sekvenční záblesková",
    mode_standard: "Standardní Soroban (Statický)",
    mode_standard_desc: "Plné zobrazení statických čísel",
    level_label: "Úroveň (Přísná pravidla Sorobanu)",
    level_l1: "L1 - Přímé sčítání/odčítání (bez doplňků)",
    level_l2: "L2 - Přátelé 5 (doplňky 5)",
    level_l3: "L3 - Přátelé 10 (doplňky 10)",
    level_lm: "LM - Smíšené komplexní (všechna pravidla)",
    age_label: "Věková skupina",
    age_under_6: "Méně než 6 let",
    age_7_9: "7 - 9 let",
    age_10_12: "10 - 12 let",
    age_13_15: "13 - 15 let",
    age_16_plus: "16+ let",
    digits_label: "Číslice",
    rows_label: "Řádky",
    op_label: "Typ operace",
    op_add: "Pouze sčítání",
    op_sub: "Pouze odčítání",
    op_mix: "Smíšené (sčítání a odčítání)",
    duration_label: "Čas výzvy (s)",
    rest_label: "Doba odpočinku",
    rest_1s: "1 sekunda",
    rest_2s: "2 sekundy",
    rest_3s: "3 sekundy",
    rest_4s: "4 sekundy",
    rest_5s: "5 sekund",
    speed_label: "Rychlost zobrazení (sekundy)",
    tts_label: "Výslovnost čísel",
    start_button: "Spustit výzvu",
    timer_label: "Zbývající čas:",
    score_label: "Skóre:",
    exit_button: "Ukončit",
    submit_answer: "Odeslat odpověď",
    welcome_title: "Vítejte v Mizan Anzan",
    welcome_desc: "Zaregistrujte své údaje pro vytvoření sledovacího kódu",
    fullname_label: "Celé jméno génia",
    fullname_ph: "Zadejte své celé jméno",
    country_label: "Země",
    country_ph: "Příklad: Francie, Egypt, Saúdská Arábie",
    generate_code_btn: "Vygenerovat kód génia a vstoupit",
    countdown_start: "START!",
    generation_error: "S těmito nastaveními nelze vygenerovat platnou výzvu.",
    correct_feedback: "Správná odpověď! Skvělá práce, génie.",
    incorrect_feedback: "Nesprávné. Správná odpověď byla:",
    invalid_integer: "Zadejte platné celé číslo.",
    challenge_complete: "Výzva dokončena!",
    total_score: "Celkové skóre:",
    correct_answers: "Správné odpovědi:",
    of_word: "z",
    trainer_title: "Ovládací panel trenéra",
    parent_title: "Panel pokroku rodičů",
    portal_desc: "Zadejte kód génia pro zobrazení pokroku a podrobné analýzy",
    lookup_placeholder: "Zadejte kód génia (např. ANZ-982143)",
    follow_up: "Zobrazit",
    enter_code: "Zadejte kód génia",
    tracked_student: "Sledovaný génius:",
    active_account: "Aktivní registrovaný účet",
    genius_fallback: "Anzan Génius",
    focus_metric: "Zaměření",
    accuracy_metric: "Přesnost",
    perf_metric: "Výkon a rychlost",
    growth_metric: "Růst",
    th_rank: "#",
    th_code: "Kód",
    th_country: "Země",
    th_name: "Jméno génia",
    th_mode: "Režim",
    th_age: "Věková skupina",
    th_level: "Úroveň",
    th_digits: "Číslice",
    th_rows: "Řádky",
    th_operation: "Operace",
    th_duration: "Doba trvání",
    th_speed: "Rychlost",
    th_points: "Body",
    leaderboard_title: "Žebříček — Top 20",
    leaderboard_empty: "Zatím žádné výsledky.",
    mode_flash_short: "Flash Anzan",
    mode_standard_short: "Standardní Soroban",
    op_add_short: "Sčítání",
    op_sub_short: "Odčítání",
    op_mix_short: "Smíšené",
    subtract_speech: "Odčítání",
    seconds_short: "s",
    challenge_invalid: "Výzvu nelze spustit. Zkontrolujte nastavení a zkuste to znovu.",
    challenge_generation_failed: "Výzvu nelze vygenerovat. Test se nespustil. Zkontrolujte nastavení tréninku.",
    save_failed: "Výsledek výzvy nelze uložit na server. Tento pokus nebyl započítán do zpráv nebo žebříčku.",
    save_success: "Výsledek byl úspěšně uložen a propojen s kódem studenta.",
    save_queued: "Server je dočasně nedostupný. Tento pokus byl uložen lokálně a bude automaticky synchronizován po obnovení připojení.",
    open_report_prompt: "Chcete otevřít zprávu nyní?",
    loading_data: "Načítání údajů...",
    monthly_failed: "Nepodařilo se načíst géniy měsíce.",
    monthly_title: "Géniové měsíce",
    sessions_metric: "Relácie",
    questions_metric: "Otázky",
    points_metric: "Body",
    streak_metric: "Nejlepší série",
    student_not_found: "Student nebyl nalezen nebo údaje se nepodařilo načíst.",
    result_title: "Výzva dokončena!",
    result_subtitle: "Váš výsledek výzvy je připraven k kontrole.",
    result_score: "Celkové skóre:",
    result_correct: "Správné odpovědi:",
    result_saved: "Výsledek byl úspěšně uložen a propojen s kódem studenta.",
    result_open_report: "Otevřít zprávu",
    result_continue: "Pokračovat",
    version_label: "Soroban Core v3.1",
    registration_title: "Vítejte v MIZAN ANZAN",
    registration_desc: "Vytvořte si svou bezpečnou identitu MIZAN a pokračujte ve své personalizované vzdělávací cestě.",
    registration_language_label: "Jazyk registrace",
    registration_language_desc: "Vyberte jazyk, který chcete používat v průběhu celého vašeho zážitku s MIZAN.",
    role_selection_title: "Vyberte typ svého účtu",
    role_selection_desc: "Vyberte typ účtu, který nejlépe popisuje, jak budete MIZAN používat.",
    role_genius: "Genius",
    role_genius_desc: "Pro studenty, kteří chtějí trénovat, zlepšovat se a sledovat svůj vlastní pokrok.",
    role_coach: "Trenér",
    role_coach_desc: "Pro trenéry, kteří řídí výuku, trénink a pokrok studentů.",
    role_parent: "Rodič",
    role_parent_desc: "Pro rodiče nebo opatrovníky, kteří chtějí sledovat pokrok svého dítěte.",
    role_entity: "Organizace",
    role_entity_desc: "Pro školy, akademie, centra, instituty, kluby, federace a tréninkové organizace.",
    genius_full_name_label: "Celé jméno génia",
    genius_full_name_placeholder: "Zadejte své celé jméno",
    display_name_en_label: "Mezinárodní jméno v angličtině",
    display_name_en_placeholder: "Zadejte své jméno v angličtině",
    display_name_en_help: "Toto jméno bude použito na mezinárodních žebříčcích, soutěžích a globálním uznání.",
    display_name_en_required: "Vaše mezinárodní anglické jméno je povinné.",
    display_name_en_invalid: "Zadejte prosím platné mezinárodní jméno pomocí anglických písmen.",
    display_name_en_confirm: "Potvrzuji, že toto je anglické jméno, které chci používat mezinárodně.",
    country_placeholder: "Vyberte svou zemi",
    country_search_placeholder: "Vyhledejte svou zemi",
    country_help: "Vaše země bude použita pro mezinárodní žebříčky a soutěže.",
    entity_name_label: "Název organizace",
    entity_name_placeholder: "Zadejte název organizace",
    entity_type_label: "Typ organizace",
    branch_label: "Pobočka",
    branch_placeholder: "Vyberte pobočku",
    branch_optional: "Výběr pobočky je nepovinný",
    branch_main: "Hlavní organizace",
    independent_coach: "Nezávislý trenér",
    independent_coach_title: "Nezávislý trenér",
    independent_coach_desc: "Zaregistrujte se jako nezávislý trenér bez připojení k organizaci.",
    independent_coach_note: "Nezávislí trenéři se mohou registrovat bez organizace nebo pobočky.",
    coach_registration_title: "Registrace trenéra",
    coach_registration_desc: "Vytvořte si svůj profesionální MIZAN trenérský účet.",
    coach_code_label: "Trenérský kód",
    parent_registration_title: "Registrace rodiče",
    parent_registration_desc: "Vytvořte si svůj bezpečný rodičovský nebo opatrovnický účet.",
    parent_code_label: "Rodičovský kód",
    entity_code_label: "Kód organizace",
    entity_code_placeholder: "Zadejte kód své organizace",
    entity_code_help: "Použijte tento kód pro přístup k MIZAN účtu vaší organizace.",
    create_account_button: "Vytvořit účet",
    create_genius_account_button: "Vytvořit geniální účet",
    create_coach_account_button: "Vytvořit trenérský účet",
    create_parent_account_button: "Vytvořit rodičovský účet",
    create_organization_account_button: "Vytvořit organizační účet",
    registration_success_title: "Registrace úspěšná",
    registration_success_desc: "Váš MIZAN účet byl úspěšně vytvořen.",
    your_genius_code: "Váš geniální kód",
    your_coach_code: "Váš trenérský kód",
    your_parent_code: "Váš rodičovský kód",
    your_organization_code: "Váš organizační kód",
    save_code_warning: "Uložte si svůj kód na bezpečném místě. Budete ho potřebovat pro přístup k vašemu MIZAN účtu.",
    link_genius_title: "Propojit génia",
    link_genius_desc: "Zadejte geniální kód poskytnutý studentem.",
    genius_code_label: "Geniální kód",
    genius_code_placeholder: "Příklad: ANZ-982143",
    link_genius_button: "Propojit génia",
    registration_failed: "Registraci se nepodařilo dokončit.",
    server_error: "Nepodařilo se nám dokončit vaši registraci. Zkuste to prosím znovu.",
    required_field: "Toto pole je povinné.",
    invalid_name: "Zadejte prosím platné jméno.",
    invalid_english_name: "Zadejte prosím platné mezinárodní jméno v angličtině.",
    country_required: "Vyberte prosím svou zemi.",
    role_required: "Vyberte prosím typ účtu.",
    entity_required: "Zadejte prosím informace o vaší organizaci.",
    branch_required: "Vyberte prosím pobočku.",
    code_invalid: "Kód je neplatný.",
    code_not_found: "Kód nebyl nalezen.",
    code_already_used: "Tento kód je již používán.",
    network_error: "Došlo k chybě připojení. Zkuste to prosím znovu.",
    back_button: "Zpět",
    continue_button: "Pokračovat",
    cancel_button: "Zrušit",
    change_account_type: "Změnit typ účtu",
    switch_account: "Přepnout účet",
    language_label: "Jazyk",
    change_language: "Změnit jazyk",
    language_saved: "Jazykové preference byly uloženy.",
    language_loading: "Načítání jazyka...",
    language_unavailable: "Tento jazyk je dočasně nedostupný.",
    monthly_award_label: "Géniové měsíce",
    monthly_description: "Géniové měsíce",
    reports_label: "Otevřít zprávu",
    cognitive_profile_label: "Zaměření",
    entity_type_school: "Pro školy",
    entity_type_academy: "akademie",
    entity_type_center: "centra",
    entity_type_institute: "instituty",
    entity_type_club: "kluby",
    entity_type_educational_institution: "Vzdělávací instituce",
    entity_type_federation: "tréninkové organizace",
    entity_type_training_organization: "Typ organizace",
    entity_type_other: "Jiné",
    organization_country: "Země",
    organization_city: "Město",
    branch_code: "Pobočka — Kód organizace",
    branch_name: "Pobočka — Název organizace",
    branch_manager: "Vedoucí pobočky",
    international_name_privacy: "Toto jméno bude použito na mezinárodních žebříčcích, soutěžích a globálním uznání.",
    leaderboard_name_notice: "Toto jméno bude použito na mezinárodních žebříčcích, soutěžích a globálním uznání.",
    privacy_notice: "Vytvořte si svou bezpečnou identitu MIZAN a pokračujte ve své personalizované vzdělávací cestě."
};
